<?php

namespace Database\Seeders;

use App\Models\KebijakanPrivasi;
use Illuminate\Database\Seeder;

class KebijakanPrivasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $daftarKebijakanPrivasi = [
            [
                "nama_kebijakan" => "Pemberitahuan privasi ini menjelaskan hal-hal berikut",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 1
            ],
            [
                "nama_kebijakan" => "Koleksi Informasi Pribadi",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 2
            ],
            [
                "nama_kebijakan" => "Tujuan mengumpulkan informasi anda",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 3
            ],
            [
                "nama_kebijakan" => "Lainnya",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 4
            ],
            [
                "nama_kebijakan" => "Pilihan Akses dan Informasi Pribadi",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 5
            ],
            [
                "nama_kebijakan" => "Retensi Informasi Pribadi",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 6
            ],
            [
                "nama_kebijakan" => "Keamanan Informasi Pribadi",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 7
            ],
            [
                "nama_kebijakan" => "Kemana saja informasi pribadi ditutup",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 8
            ],
            [
                "nama_kebijakan" => "Kewajiban anda mengenai informasi pribadi anda",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 9
            ],
            [
                "nama_kebijakan" => "Transfer dari informasi pribadi anda di luar yuridiksi lokal anda",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 10
            ],
            [
                "nama_kebijakan" => "Situs Terkait",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 11
            ],
            [
                "nama_kebijakan" => "Persyaratan Anda",
                "deskripsi_kebijakan" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nisi diam, tincidunt vitae nisl sit amet, mattis venenatis ligula. Morbi euismod lorem non efficitur rutrum. Nunc semper est risus, ac consectetur sapien consectetur id. Morbi dui massa, fringilla ac ullamcorper et, accumsan vitae mauris. Nunc placerat odio non leo scelerisque bibendum. In tincidunt felis placerat, condimentum ex quis, lobortis sapien. Etiam sit amet sapien commodo, lobortis enim sit amet, scelerisque nibh. Nullam at molestie elit. Curabitur pulvinar sapien sed ipsum mollis eleifend a in arcu. Sed malesuada nibh vestibulum dolor scelerisque elementum. Cras id nibh cursus, semper quam vitae, viverra nunc. Etiam pulvinar justo arcu, et faucibus nulla sollicitudin eget. Quisque pretium sit amet urna in semper. Etiam molestie, neque et condimentum gravida, nibh libero efficitur sem, vitae maximus lacus urna at eros. Aliquam fermentum orci tortor, a lacinia tortor malesuada non.</p><p>Mauris porta velit ac ligula feugiat convallis. Fusce sodales vitae magna at iaculis. Aenean non tellus dictum, mollis massa sed, tristique odio. Donec laoreet risus sed dui pulvinar, sit amet tempus purus gravida. Mauris sed diam dolor. Integer sit amet felis tincidunt metus imperdiet aliquam vitae faucibus felis. Aliquam turpis nisi, eleifend et libero eget, ultrices sagittis massa. Mauris vehicula ullamcorper metus, non cursus dolor feugiat nec. Nunc lacinia mollis neque ac consectetur. Aliquam vitae laoreet erat, eu pretium nisi. Maecenas sed mi dui. Curabitur turpis nisi, consectetur in blandit et, dapibus aliquet elit. Nulla neque purus, hendrerit eu euismod non, imperdiet vitae elit.</p><p>Praesent et faucibus dui. Fusce congue egestas mi id elementum. Nam maximus enim quis justo sodales congue. Sed non nisi non risus porta ultricies sed lobortis ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent est erat, maximus cursus auctor ut, lacinia vel orci. Sed gravida dolor vel libero hendrerit fermentum.</p>",
                "urutan" => 12
            ]
        ];

        foreach ($daftarKebijakanPrivasi as $item) {
            KebijakanPrivasi::create($item);
        }
    }
}
