<?php

namespace Database\Seeders;

use App\Models\Programstudi;
use Illuminate\Database\Seeder;

class ProgramstudiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $program_studi = [
            ["id" => 1, "nama" => "Konstruksi Gedung, Sanitasi dan Perawatan"],
            ["id" => 2, "nama" => "Konstruksi Jalan, Irigasi dan Jembatan"],
            ["id" => 3, "nama" => "Bisnis Konstruksi dan Properti"],
            ["id" => 4, "nama" => "Desain Pemodelan dan Informasi Bangunan"],
            ["id" => 5, "nama" => "Teknik Geomatika"],
            ["id" => 6, "nama" => "Informasi Geospasial"],
            ["id" => 7, "nama" => "Teknik Pembangkit Tenaga Listri"],
            ["id" => 8, "nama" => "Teknik Jaringan Tenaga Listrik"],
            ["id" => 9, "nama" => "Teknik Instalasi Tenaga Listrik"],
            ["id" => 10, "nama" => "Teknik Otomasi Industri"],
            ["id" => 11, "nama" => "Teknik Pendinginan dan Tata Udara"],
            ["id" => 12, "nama" => "Teknik Tenaga Listri"],
            ["id" => 13, "nama" => "Teknik Pemesinan"],
            ["id" => 14, "nama" => "Teknik Pengelasan"],
            ["id" => 15, "nama" => "Teknik Pengecoran Logam"],
            ["id" => 16, "nama" => "Teknik Mekanik Industri"],
            ["id" => 17, "nama" => "Teknik Perancangan dan Gambar Mesin"],
            ["id" => 18, "nama" => "Teknik Fabrikasi Logam dan Manufaktu"],
            ["id" => 19, "nama" => "Airframe Power Plant"],
            ["id" => 20, "nama" => "Aircraft Machining"],
            ["id" => 21, "nama" => "Aircraft Sheet Metal Forming"],
            ["id" => 22, "nama" => "Airframe Mechanic"],
            ["id" => 23, "nama" => "Aircraft Electricity"],
            ["id" => 24, "nama" => "Aviation Electronics"],
            ["id" => 25, "nama" => "Desain Grafika"],
            ["id" => 26, "nama" => "Produksi Grafika"],
            ["id" => 27, "nama" => "Teknik Instrumentasi Loga"],
            ["id" => 28, "nama" => "Instrumentasi dan Otomatisasi Proses"],
            ["id" => 29, "nama" => "Teknik Pengendalian Produksi"],
            ["id" => 30, "nama" => "Teknik Tata Kelola Logistik"],
            ["id" => 31, "nama" => "Teknik Pemintalan Serat Buatan"],
            ["id" => 32, "nama" => "Teknik Pembuatan Benang"],
            ["id" => 33, "nama" => "Teknik Pembuatan Kain"],
            ["id" => 34, "nama" => "Teknik Penyempurnaan Tekstil"],
            ["id" => 35, "nama" => "Analisis Pengujian Laboratorium"],
            ["id" => 36, "nama" => "Kimia Industri"],
            ["id" => 37, "nama" => "Kimia Analisis"],
            ["id" => 38, "nama" => "Kimia Tekstil"],
            ["id" => 39, "nama" => "Teknik Kendaraan Ringan Otomotif"],
            ["id" => 40, "nama" => "Teknik dan Bisnis Sepeda Motor"],
            ["id" => 41, "nama" => "Teknik Alat Berat"],
            ["id" => 42, "nama" => "Teknik Bodi Otomotif"],
            ["id" => 43, "nama" => "Teknik Ototronik"],
            ["id" => 44, "nama" => "Teknik dan Manajemen Perawatan Otomotif"],
            ["id" => 45, "nama" => "Otomotif Daya dan Konversi Energi"],
            ["id" => 46, "nama" => "Konstruksi Kapal Baja"],
            ["id" => 47, "nama" => "Konstruksi Kapal Non Baja"],
            ["id" => 48, "nama" => "Teknik Pemesinan Kapal"],
            ["id" => 49, "nama" => "Teknik Pengelasan Kapal"],
            ["id" => 50, "nama" => "Teknik Kelistrikan Kapal"],
            ["id" => 51, "nama" => "Desain dan Rancang Bangun Kapal"],
            ["id" => 52, "nama" => "Interior Kapal"],
            ["id" => 53, "nama" => "Teknik Audio Video"],
            ["id" => 54, "nama" => "Teknik Elektronika Industri"],
            ["id" => 55, "nama" => "Teknik Mekatronika"],
            ["id" => 56, "nama" => "Teknik Elektronika Daya dan Komunikasi"],
            ["id" => 57, "nama" => "Instrumentasi Medik"],
            ["id" => 58, "nama" => "Teknik Produksi Minyak dan Gas"],
            ["id" => 59, "nama" => "Teknik Pemboran Minyak dan Gas"],
            ["id" => 60, "nama" => "Teknik Pengolahan Minyak, Gas dan Petrokimia"],
            ["id" => 61, "nama" => "Geologi Pertambangan"],
            ["id" => 62, "nama" => "Teknik Energi Surya, Hidro, dan Angin"],
            ["id" => 63, "nama" => "Teknik Energi Biomassa"],
            ["id" => 64, "nama" => "Rekayasa Perangkat Lunak"],
            ["id" => 65, "nama" => "Teknik Komputer dan Jaringan"],
            ["id" => 66, "nama" => "Sistem Informatika, Jaringan dan Aplikasi"],
            ["id" => 67, "nama" => "Teknik Transmisi Telekomunikas"],
            ["id" => 68, "nama" => "Teknik Jaringan Akses Telekomunikasi"],
            ["id" => 69, "nama" => "Asisten Keperawatan"],
            ["id" => 70, "nama" => "Dental Asisten"],
            ["id" => 71, "nama" => "Teknologi Laboratorium Medik"],
            ["id" => 72, "nama" => "Farmasi Klinis dan Komunitas"],
            ["id" => 73, "nama" => "Farmasi Industri"],
            ["id" => 74, "nama" => "Social Care (Keperawatan Sosial)"],
            ["id" => 75, "nama" => "Caregiver"],
            ["id" => 76, "nama" => "Agribisnis Tanaman Pangan dan Hortikultura"],
            ["id" => 77, "nama" => "Agribisnis Tanaman Perkebunan"],
            ["id" => 78, "nama" => "Pemuliaan dan Perbenihan Tanaman"],
            ["id" => 79, "nama" => "Lanskap dan Pertamanan"],
            ["id" => 80, "nama" => "Produksi dan Pengelolaan Perkebunan"],
            ["id" => 81, "nama" => "Agribisnis Organik Ekologi"],
            ["id" => 82, "nama" => "Agribisnis Ternak Ruminansia"],
            ["id" => 83, "nama" => "Agribisnis Ternak Unggas"],
            ["id" => 84, "nama" => "Industri Peternakan"],
            ["id" => 85, "nama" => "Keperawatan Hewan"],
            ["id" => 86, "nama" => "Kesehatan dan Reproduksi Hewan"],
            ["id" => 87, "nama" => "Agribisnis Pengolahan Hasil Pertanian"],
            ["id" => 88, "nama" => "Pengawasan Mutu Hasil Pertanian"],
            ["id" => 89, "nama" => "Agroindustri"],
            ["id" => 90, "nama" => "Alat Mesin Pertanian"],
            ["id" => 91, "nama" => "Otomatisasi Pertanian"],
            ["id" => 92, "nama" => "Teknik Inventarisasi dan Pemetaan Hutan"],
            ["id" => 93, "nama" => "Teknik Konservasi Sumber Daya Alam"],
            ["id" => 94, "nama" => "Teknik Rehabilitasi dan Reklamasi Hutan"],
            ["id" => 95, "nama" => "Teknologi Produksi Hasil Hutan"],
            ["id" => 96, "nama" => "Nautika Kapal Penangkap Ikan"],
            ["id" => 97, "nama" => "Teknika Kapal Penangkap Ikan"],
            ["id" => 98, "nama" => "Nautika Kapal Niaga"],
            ["id" => 99, "nama" => "Teknika Kapal Niaga"],
            ["id" => 100, "nama" => "Agribisnis Perikanan Air Tawar"],
            ["id" => 101, "nama" => "Agribisnis Perikanan Air Payau dan Laut"],
            ["id" => 102, "nama" => "Agribisnis Ikan Hias"],
            ["id" => 103, "nama" => "Agribisnis Rumput Laut"],
            ["id" => 104, "nama" => "Industri Perikanan Laut"],
            ["id" => 105, "nama" => "Agribisnis Pengolahan Hasil Perikanan"],
            ["id" => 106, "nama" => "Bisnis Daring dan Pemasaran"],
            ["id" => 107, "nama" => "Otomatisasi dan Tata Kelola Perkantoran"],
            ["id" => 108, "nama" => "Akuntansi dan Keuangan Lembaga"],
            ["id" => 109, "nama" => "Perbankan dan Keuangan Mikro"],
            ["id" => 110, "nama" => "Perbankan Syariah"],
            ["id" => 111, "nama" => "Usaha Perjalanan Wisata"],
            ["id" => 112, "nama" => "Wisata Bahari dan Ekowisata"],
            ["id" => 113, "nama" => "Tata Boga"],
            ["id" => 114, "nama" => "Tata Kecantikan Kulit dan Rambut"],
            ["id" => 115, "nama" => "Spa dan Beauty Therapy"],
            ["id" => 116, "nama" => "Tata Busana"],
            ["id" => 117, "nama" => "Desain Fesyen"],
            ["id" => 118, "nama" => "Seni Lukis"],
            ["id" => 119, "nama" => "Seni Patung"],
            ["id" => 120, "nama" => "Desain Komunikasi Visual"],
            ["id" => 121, "nama" => "Desain Interior dan Teknik Furnitur"],
            ["id" => 122, "nama" => "Animasi"],
            ["id" => 123, "nama" => "Kriya Kreatif Batik dan Tekstil"],
            ["id" => 124, "nama" => "Kriya Kreatif Kulit dan Imitasi"],
            ["id" => 125, "nama" => "Kriya Kreatif Keramik"],
            ["id" => 126, "nama" => "Kriya Kreatif Logam dan Perhiasan"],
            ["id" => 127, "nama" => "Kriya Kreatif Kayu dan Rotan"],
            ["id" => 128, "nama" => "Seni Musik Klasik"],
            ["id" => 129, "nama" => "Seni Musik Populer"],
            ["id" => 130, "nama" => "Seni Tari"],
            ["id" => 131, "nama" => "Penataan Tari"],
            ["id" => 132, "nama" => "Seni Karawitan"],
            ["id" => 133, "nama" => "Penataan Karawitan"],
            ["id" => 134, "nama" => "Seni Pedalangan"],
            ["id" => 135, "nama" => "Pemeranan"],
            ["id" => 136, "nama" => "Tata Artistik Teater"],
            ["id" => 137, "nama" => "Produksi dan Siaran Program Radio"],
            ["id" => 138, "nama" => "Produksi dan Siaran Program Televisi"],
            ["id" => 139, "nama" => "Produksi Film dan Program Televisi"],
            ["id" => 140, "nama" => "Teknik Gambar Bangunan"],
            ["id" => 141, "nama" => "Multimedia"],
            ["id" => 142, "nama" => "SMA - IPA"],
            ["id" => 143, "nama" => "SMA - IPS"],
            ["id" => 144, "nama" => "Teknik Konstruksi Baja"],
            ["id" => 145, "nama" => "Teknik Konstruksi Kayu"],
            ["id" => 146, "nama" => "Teknik Konstruksi Batu dan Beton"],
            ["id" => 147, "nama" => "Teknik Gambar Bangunan"],
            ["id" => 148, "nama" => "Teknik Furniture"],
            ["id" => 149, "nama" => "Teknik Plumbing dan Sanitasi"],
            ["id" => 150, "nama" => "Teknik Survei dan Pemetaan"],
            ["id" => 151, "nama" => "Teknik Pembangkit Tenaga Listrik"],
            ["id" => 152, "nama" => "Teknik Distribusi Tenaga Listrik"],
            ["id" => 153, "nama" => "Teknik Transmisi Tenaga Listrik"],
            ["id" => 154, "nama" => "Teknik Instalasi Tenaga Listrik"],
            ["id" => 155, "nama" => "Teknik Otomasi Industri"],
            ["id" => 156, "nama" => "Teknik Pendingan dan Tata Udara"],
            ["id" => 157, "nama" => "Teknik Pemesinan"],
            ["id" => 158, "nama" => "Teknik Pengelasan"],
            ["id" => 159, "nama" => "Teknik Fabrikasi Logam"],
            ["id" => 160, "nama" => "Teknik Pengecoran Logam"],
            ["id" => 161, "nama" => "Teknik Gambar Mesin"],
            ["id" => 162, "nama" => "Teknik Pemeliharaan Mekanik Industri"],
            ["id" => 163, "nama" => "Teknik Kendaraan Ringan"],
            ["id" => 164, "nama" => "Teknik Sepeda Motor"],
            ["id" => 165, "nama" => "Teknik Perbaikan Bodi Otomotif"],
            ["id" => 166, "nama" => "Teknik Alat Berat"],
            ["id" => 167, "nama" => "Teknik Ototronik"],
            ["id" => 168, "nama" => "Air Frame dan Power Plant"],
            ["id" => 169, "nama" => "Pemesinan Pesawat Udara"],
            ["id" => 170, "nama" => "Konstruksi Badan Pesawat Udara"],
            ["id" => 171, "nama" => "Konstruksi Rangka Pesawat Udara"],
            ["id" => 172, "nama" => "Kelistrikan Pesawat Udara"],
            ["id" => 173, "nama" => "Elektronika Pesawat Udara"],
            ["id" => 174, "nama" => "Pemeliharaan dan Perbaikan Instrumen Elektronika"],
            ["id" => 175, "nama" => "Teknik Konstruksi Kapal Baja"],
            ["id" => 176, "nama" => "Teknik Konstruksi Kapal Kayu"],
            ["id" => 177, "nama" => "Teknik Konstruksi Kapa Fiberglas"],
            ["id" => 178, "nama" => "Teknik Instalasi Pemesinan Kapal"],
            ["id" => 179, "nama" => "Teknik Pengelasan Kapal"],
            ["id" => 180, "nama" => "Kelistrikan Kapal"],
            ["id" => 181, "nama" => "Teknik Gambar Rancang Bangun Kapal"],
            ["id" => 182, "nama" => "Interior Kapal"],
            ["id" => 183, "nama" => "Teknik Pemintalan Serat Buatan"],
            ["id" => 184, "nama" => "Teknik Pembuatan Benang"],
            ["id" => 185, "nama" => "Teknik Pembuatan Kain"],
            ["id" => 186, "nama" => "Teknik Penyempuraan Tekstil"],
            ["id" => 187, "nama" => "Garmen"],
            ["id" => 188, "nama" => "Persiapan Grafika"],
            ["id" => 189, "nama" => "Produksi Grafika"],
            ["id" => 190, "nama" => "Geologi Pertambangan"],
            ["id" => 191, "nama" => "Teknik Instrumentasi Gelas"],
            ["id" => 192, "nama" => "Teknik Instrumentasi Logam"],
            ["id" => 193, "nama" => "Kontrol Proses"],
            ["id" => 194, "nama" => "Kontrok Mekanik"],
            ["id" => 195, "nama" => "Kimia Analisis"],
            ["id" => 196, "nama" => "Kimia Industri"],
            ["id" => 197, "nama" => "Neutika Kapal Penangkap Ikan"],
            ["id" => 198, "nama" => "Teknika Kapal Penangkap Ikan"],
            ["id" => 199, "nama" => "Neutika Kapal Niaga"],
            ["id" => 200, "nama" => "Teknika Kapal Niaga"],
            ["id" => 201, "nama" => "Teknik dan Managemen Produksi"],
            ["id" => 202, "nama" => "Teknik dan Managemen Pergudangan"],
            ["id" => 203, "nama" => "Teknik dan Managemen Transportasi"],
            ["id" => 204, "nama" => "Teknik Produksi Perminyakan"],
            ["id" => 205, "nama" => "Teknik Pengeboran Minyak"],
            ["id" => 206, "nama" => "Teknik Pengolahan Mingak, Gas dan Petrokimia"],
            ["id" => 207, "nama" => "Teknik Audio Video"],
            ["id" => 208, "nama" => "Teknik Elektronika Industri"],
            ["id" => 209, "nama" => "Teknik Mekatronika"],
            ["id" => 210, "nama" => "Tekniok Konstruksi Batu dan Beton"],
            ["id" => 211, "nama" => "Teknik Furnitur"],
            ["id" => 212, "nama" => "Teknik Plambing dan Sanitasi"],
            ["id" => 213, "nama" => "Geomatika"],
            ["id" => 214, "nama" => "Teknik Jaringan Tenaga Listrik"],
            ["id" => 215, "nama" => "Teknik Instalasi Pemanfaatan Tenaga Listrik"],
            ["id" => 216, "nama" => "Teknik Pendingin dan Tata Udara"],
            ["id" => 217, "nama" => "Pemeliharaan dan Perbaikan Motor dan Rangka Pesawat Udara ( Airframe Power Plant)"],
            ["id" => 218, "nama" => "Pemesinan Pesawat Udara ( Aircraft Machining)"],
            ["id" => 219, "nama" => "Konstruksi Badan Pesawat Udara ( Aircraft Sheet Metal Forming)"],
            ["id" => 220, "nama" => "Konstruksi Rangka Pesawat Udara ( Airframe Mechanics)"],
            ["id" => 221, "nama" => "Kelistrikan Pesawat Udara ( Aircraft Electricity)"],
            ["id" => 222, "nama" => "Elektronika Pesawat Udara ( Aviation Electronis )"],
            ["id" => 223, "nama" => "Pemeliharaan dan Perbaikan Instrumen Elektronika Pesawat Udara (Electrical Avionics )"],
            ["id" => 224, "nama" => "Kontrol Mekanik"],
            ["id" => 225, "nama" => "Teknik Pelayanan Produksi"],
            ["id" => 226, "nama" => "Teknik Pergudangan"],
            ["id" => 227, "nama" => "Teknik Penyempurnaan Tekstil"],
            ["id" => 228, "nama" => "Teknik Produksi Minyak dan Gas"],
            ["id" => 229, "nama" => "Teknik Pemboran Minyak dan Gas"],
            ["id" => 230, "nama" => "Teknik Pengolahan Minyak, Gas dan Petrokimia"],
            ["id" => 231, "nama" => "Teknik Konstruksi Kapal Fiberglass"],
            ["id" => 232, "nama" => "Teknik Elektronika Komunikasi"],
            ["id" => 233, "nama" => "Teknik Energi Hidro"],
            ["id" => 234, "nama" => "Teknik Energi Surya dan Angin"],
            ["id" => 235, "nama" => "Teknik Energi Biomassa"],
            ["id" => 236, "nama" => "Teknik Transmisi Telekomunikasi"],
            ["id" => 237, "nama" => "Teknik Suitsing"],
            ["id" => 238, "nama" => "Teknik Jaringan Akses"],
            ["id" => 239, "nama" => "Rekayasa Perangkat Lunak"],
            ["id" => 240, "nama" => "Teknik Komputer dan Jaringan"],
            ["id" => 241, "nama" => "Animasi"],
            ["id" => 242, "nama" => "Multimedia"],
            ["id" => 243, "nama" => "Teknik Produksi dan Penyiaran Program Pertelevisian"],
            ["id" => 244, "nama" => "Teknik Produlsi dan Penyiaran Program Radio"],
            ["id" => 245, "nama" => "Teknik Produksi dan Penyiaran Program Radio dan Pertelevisian"],
            ["id" => 246, "nama" => "Perawat Kesehatan"],
            ["id" => 247, "nama" => "Perawat Gigi"],
            ["id" => 248, "nama" => "Analis Kesehatan"],
            ["id" => 249, "nama" => "Farmasi"],
            ["id" => 250, "nama" => "Farmasi Industri"],
            ["id" => 251, "nama" => "Perawatan Sosial"],
            ["id" => 252, "nama" => "Keperawatan"],
            ["id" => 253, "nama" => "Keperawatan Gigi"],
            ["id" => 254, "nama" => "Pekerjaan Sosial"],
            ["id" => 255, "nama" => "Agribisnis Tanaman Pangan dan Hortikultura"],
            ["id" => 256, "nama" => "Agribisnis Tanaman Perkebunan"],
            ["id" => 257, "nama" => "Agribisnis Pembibitan dan Kultur Jaringan Tanaman"],
            ["id" => 258, "nama" => "Agribisnis Ternak Ruminansia"],
            ["id" => 259, "nama" => "Agribisnis Ternak Unggas"],
            ["id" => 260, "nama" => "Agribisnis Aneka Ternak"],
            ["id" => 261, "nama" => "Perawatan Kesehatan Ternak"],
            ["id" => 262, "nama" => "Agribisnis Perikanan"],
            ["id" => 263, "nama" => "Agribisnis Rumput Laut"],
            ["id" => 264, "nama" => "Mekanisasi Pertanian"],
            ["id" => 265, "nama" => "Teknologi Pengolahan Hasil Pertanian"],
            ["id" => 266, "nama" => "Pengawasan Mutu"],
            ["id" => 267, "nama" => "Kehutanan"],
            ["id" => 268, "nama" => "Agribisnis Perbenihan dan Kultur Jaringan Tanaman"],
            ["id" => 269, "nama" => "Kesehatan Hewan"],
            ["id" => 270, "nama" => "Teknologi Pengolahan Hasil Perikanan"],
            ["id" => 271, "nama" => "Pengawasan Mutu Hasil Pertanian dan Perikanan"],
            ["id" => 272, "nama" => "Alat Mesin Pertanian"],
            ["id" => 273, "nama" => "Teknik Tanah dan Air"],
            ["id" => 274, "nama" => " Teknik Inventarisasi dan Pemetaan Hutan"],
            ["id" => 275, "nama" => "Teknik Konservasi Sumberdaya Hutan"],
            ["id" => 276, "nama" => "Teknik Rehabilitasi dan Reklamasi Hutan"],
            ["id" => 277, "nama" => "Teknik Produksi Hasil Hutan"],
            ["id" => 278, "nama" => "Administrasi Perkantoran"],
            ["id" => 279, "nama" => "Akuntansi"],
            ["id" => 280, "nama" => "Perbankan"],
            ["id" => 281, "nama" => "Pemasaran"],
            ["id" => 282, "nama" => "Perbankan Syariah"],
            ["id" => 283, "nama" => "Nautika Kapal Penangkap Ikan"],
            ["id" => 284, "nama" => "Budidaya Perikanan"],
            ["id" => 285, "nama" => "Budidaya Krustacea"],
            ["id" => 286, "nama" => "Budidaya Kekerangan"],
            ["id" => 287, "nama" => "Budidaya Rumput Laut"],
            ["id" => 288, "nama" => "Nautika Kapal Niaga"],
            ["id" => 289, "nama" => "Usaha Perjalanan Wisata"],
            ["id" => 290, "nama" => "Akomodasi Perhotelan"],
            ["id" => 291, "nama" => "Jasa Boga"],
            ["id" => 292, "nama" => "Patiseri"],
            ["id" => 293, "nama" => "Kecantikan Kulit"],
            ["id" => 294, "nama" => "Kecantikan Rambut"],
            ["id" => 295, "nama" => "Busana Butik"],
            ["id" => 296, "nama" => "Tata Kecantikan Rambut"],
            ["id" => 297, "nama" => "Tata Kecantikan Kulit"],
            ["id" => 298, "nama" => "Tata Busana"],
            ["id" => 299, "nama" => "Seni Lukis"],
            ["id" => 300, "nama" => "Seni Patung"],
            ["id" => 301, "nama" => "Desain Komunikasi Visual"],
            ["id" => 302, "nama" => "Desain Produksi Interior dan Landscaping"],
            ["id" => 303, "nama" => "Desain dan Produksi Kria Tekstil"],
            ["id" => 304, "nama" => "Desain dan Produksi Kria Kulit"],
            ["id" => 305, "nama" => "Desain dan Produksi Kria Keramik"],
            ["id" => 306, "nama" => "Desain dan Produksi Kria Logam"],
            ["id" => 307, "nama" => "Desain dan Produksi Kria Kayu"],
            ["id" => 308, "nama" => "Seni Musik Klasik"],
            ["id" => 309, "nama" => "Seni Musik Non Klasik"],
            ["id" => 310, "nama" => "Seni Tari"],
            ["id" => 311, "nama" => "Seni Kerawitan"],
            ["id" => 312, "nama" => "Seni Pedalangan"],
            ["id" => 313, "nama" => "Seni Teater"],
            ["id" => 314, "nama" => "Desain Interior"],
            ["id" => 315, "nama" => "Desain dan Produksi Kriya Tekstil"],
            ["id" => 316, "nama" => "Desain dan Produksi Kriya Kulit"],
            ["id" => 317, "nama" => "Desain dan Produksi Kriya Keramik"],
            ["id" => 318, "nama" => "Desain dan Produksi Kriya Logam"],
            ["id" => 319, "nama" => "Desain dan Produksi Kriya Kayu"],
            ["id" => 320, "nama" => "Seni Karawitan"],
            ["id" => 321, "nama" => "Pemeranan"],
            ["id" => 322, "nama" => "Tata Artistik"],
            ["id" => 323, "nama" => "Pendidikan Islam"],
            ["id" => 324, "nama" => "Teknik Konstruksi Batu Beton (TKBB)"],
            ["id" => 325, "nama" => "Kedokteran"],
            ["id" => 326, "nama" => "Kedokteran Gigi"],
            ["id" => 327, "nama" => "Kedokteran Hewan"],
            ["id" => 328, "nama" => "Kesehatan Masyarakat"],
            ["id" => 329, "nama" => "Kesehatan Lingkungan"],
            ["id" => 330, "nama" => "Ilmu Gizi"],
            ["id" => 331, "nama" => "Keselamatan &amp; Kesehatan Kerja"],
            ["id" => 332, "nama" => "Ilmu Keperawatan"],
            ["id" => 333, "nama" => "Farmasi"],
            ["id" => 334, "nama" => "Kedokteran Hewan"],
            ["id" => 335, "nama" => "Nutrisi dan Teknologi Pangan"],
            ["id" => 336, "nama" => "Kebidanan"],
            ["id" => 337, "nama" => "Fisioterafi"],
            ["id" => 338, "nama" => "Ilmu Keolahragaan"],
            ["id" => 339, "nama" => "Teknik Radiodiagnostik dan Radioterapi"],
            ["id" => 340, "nama" => "Manajemen Pelayanan Rumah Sakit"],
            ["id" => 341, "nama" => "Matematika"],
            ["id" => 342, "nama" => "Fisika"],
            ["id" => 343, "nama" => "Kimia"],
            ["id" => 344, "nama" => "Biologi"],
            ["id" => 345, "nama" => "Statistika"],
            ["id" => 346, "nama" => "Astronomi"],
            ["id" => 347, "nama" => "Bioteknologi"],
            ["id" => 348, "nama" => "Geofisika"],
            ["id" => 349, "nama" => "Meteorologi"],
            ["id" => 350, "nama" => "Geografi"],
            ["id" => 351, "nama" => "Biokimia"],
            ["id" => 352, "nama" => "Metrologi"],
            ["id" => 353, "nama" => "Aktuaria"],
            ["id" => 354, "nama" => "Statistika Terapan"],
            ["id" => 355, "nama" => "Mikrobiologi"],
            ["id" => 356, "nama" => "Bioentrepreneurship"],
            ["id" => 357, "nama" => "Ilmu Pangan (Food Science)"],
            ["id" => 358, "nama" => "Matematika Bisnis"],
            ["id" => 359, "nama" => "Fisika Medis"],
            ["id" => 360, "nama" => "Kartografi dan Penginderaan Jauh"],
            ["id" => 361, "nama" => "Pengelolaan dan Pemberdayaan SDA dan Lingkungan"],
            ["id" => 362, "nama" => "Sosial dan Humaniora"],
            ["id" => 363, "nama" => "llmu Politik"],
            ["id" => 364, "nama" => "Filsafat"],
            ["id" => 365, "nama" => "Kriminologi"],
            ["id" => 366, "nama" => "Psikologi"],
            ["id" => 367, "nama" => "Ilmu Hukum"],
            ["id" => 368, "nama" => "Sosiologi"],
            ["id" => 369, "nama" => "Jurnalistik"],
            ["id" => 370, "nama" => "Antropologi"],
            ["id" => 371, "nama" => "Hubungan Internasional (HI)"],
            ["id" => 372, "nama" => "Ilmu Kesejahteraan Sosial"],
            ["id" => 373, "nama" => "Ilmu Pemerintahan"],
            ["id" => 374, "nama" => "Administrasi Publik"],
            ["id" => 375, "nama" => "Administrasi Bisnis"],
            ["id" => 376, "nama" => "Ilmu Komunikasi"],
            ["id" => 377, "nama" => "Hubungan Masyarakat"],
            ["id" => 378, "nama" => "Marketing Communication"],
            ["id" => 379, "nama" => "Penyiaran (Broadcasting)"],
            ["id" => 380, "nama" => "Periklanan (Advertiing)"],
            ["id" => 381, "nama" => "Peradilan Agama"],
            ["id" => 382, "nama" => "Politik Islam"],
            ["id" => 383, "nama" => "Pembangunan Sosial dan Kesejahteraan"],
            ["id" => 384, "nama" => "Business Law"],
            ["id" => 385, "nama" => "Manajemen Komunikasi"],
            ["id" => 386, "nama" => "Branding"],
            ["id" => 387, "nama" => "Kearsipan"],
            ["id" => 388, "nama" => "Sains Komunikasi dan Pengembangan Masyarakat"],
            ["id" => 389, "nama" => "Ilmu Keluarga dan Konsumen"],
            ["id" => 390, "nama" => "Manajemen Produksi Media"],
            ["id" => 391, "nama" => "Ekonomi dan Bisnis Akuntansi"],
            ["id" => 392, "nama" => "Manajemen Keuangan"],
            ["id" => 393, "nama" => "Menajemen Sumber Daya Manusia dan Organisasi"],
            ["id" => 394, "nama" => "Manajemen Operasi"],
            ["id" => 395, "nama" => "Manajemen Pemasaran"],
            ["id" => 396, "nama" => "Administrasi Fiskal"],
            ["id" => 397, "nama" => "Ekonomi"],
            ["id" => 398, "nama" => "Bisnis Internasional"],
            ["id" => 399, "nama" => "Manajemen Informatika"],
            ["id" => 400, "nama" => "Ekonomi Pembangunan"],
            ["id" => 401, "nama" => "Techopreneurship"],
            ["id" => 402, "nama" => "Green Economy"],
            ["id" => 403, "nama" => "Manajemen Bisnis"],
            ["id" => 404, "nama" => "Administrasi Niaga"],
            ["id" => 405, "nama" => "Manajemen Keuangan Syariah"],
            ["id" => 406, "nama" => "Bisnis Islam"],
            ["id" => 407, "nama" => "Business Creation"],
            ["id" => 408, "nama" => "Kewirausahaan"],
            ["id" => 409, "nama" => "Manajemen Bisnis dan Pemasaran"],
            ["id" => 410, "nama" => "Manajemen Bisnis Internasional"],
            ["id" => 411, "nama" => "Ekonomi Syariah"],
            ["id" => 412, "nama" => "Keuangan"],
            ["id" => 413, "nama" => "Pemasaran Internasional"],
            ["id" => 414, "nama" => "Ekonomi Bisnis"],
            ["id" => 415, "nama" => "Akuntansi Bisnis"],
            ["id" => 416, "nama" => "Manajemen Pariwisata"],
            ["id" => 417, "nama" => "Manajemen"],
            ["id" => 418, "nama" => "Manajemen Transportasi"],
            ["id" => 419, "nama" => "Akuntansi Sektor Publik"],
            ["id" => 420, "nama" => "Manajemen Industri Katering"],
            ["id" => 421, "nama" => "Administrasi Keuangan"],
            ["id" => 422, "nama" => "Manajemen Bisnis Telekomunikasi Informatika"],
            ["id" => 423, "nama" => "Sastra dan Budaya Ilmu Sejarah"],
            ["id" => 424, "nama" => "Sastra Inggris"],
            ["id" => 425, "nama" => "Arkeologi"],
            ["id" => 426, "nama" => "Sastra Jawa"],
            ["id" => 427, "nama" => "Sastra Arab"],
            ["id" => 428, "nama" => "Sastra Jepang"],
            ["id" => 429, "nama" => "Sastra Indonesia"],
            ["id" => 430, "nama" => "Sastra Rusia"],
            ["id" => 431, "nama" => "Sastra Perancis"],
            ["id" => 432, "nama" => "Sastra Korea"],
            ["id" => 433, "nama" => "Sastra Jerman"],
            ["id" => 434, "nama" => "Sastra Belanda"],
            ["id" => 435, "nama" => "Sastra Cina"],
            ["id" => 436, "nama" => "Sastra Sunda"],
            ["id" => 437, "nama" => "Sastra Bali"],
            ["id" => 438, "nama" => "Sastra Slavia"],
            ["id" => 439, "nama" => "Sastra Minangkabau"],
            ["id" => 440, "nama" => "Sastra Nusantara"],
            ["id" => 441, "nama" => "Sejarah dan Kebudayaan Islam"],
            ["id" => 442, "nama" => "Komputer dan Teknologi Teknik Informatika"],
            ["id" => 443, "nama" => "Mobile Application &amp; Technology"],
            ["id" => 444, "nama" => "Sistem Informasi (Manajemen Informatika)"],
            ["id" => 445, "nama" => "Teknologi Game"],
            ["id" => 446, "nama" => "Ilmu Komputasi"],
            ["id" => 447, "nama" => "Cyber Security"],
            ["id" => 448, "nama" => "Bioinformatika"],
            ["id" => 449, "nama" => "Sistem Komputer (Teknik Komputer)"],
            ["id" => 450, "nama" => "Sistem Informasi Bisnis"],
            ["id" => 451, "nama" => "Software Engineering"],
            ["id" => 452, "nama" => "Sistem dan Teknologi Informasi"],
            ["id" => 453, "nama" => "Computerized Accounting"],
            ["id" => 454, "nama" => "Information Systems Audit"],
            ["id" => 455, "nama" => "Accounting Information"],
            ["id" => 456, "nama" => "Audio Engineering"],
            ["id" => 457, "nama" => "Ilmu Komputer"],
            ["id" => 458, "nama" => "Human Computer Interaction"],
            ["id" => 459, "nama" => "Pendidikan Pendidikan Guru Sekolah Dasar (PGSD)"],
            ["id" => 460, "nama" => "Manajemen Pendidikan"],
            ["id" => 461, "nama" => "Kurikulum dan Teknologi Pendidikan"],
            ["id" => 462, "nama" => "Pendidikan Luar Sekolah"],
            ["id" => 463, "nama" => "Pendidikan Luar Biasa (PLB)"],
            ["id" => 464, "nama" => "Pendidikan Anak Usia Dini (PAUD)"],
            ["id" => 465, "nama" => "Administrasi Pendidikan"],
            ["id" => 466, "nama" => "Pendidikan Bimbingan Konseling"],
            ["id" => 467, "nama" => "Ilmu Perpustakaan"],
            ["id" => 468, "nama" => "Teologi"],
            ["id" => 469, "nama" => "Pendidikan Kependudukan"],
            ["id" => 470, "nama" => "Tafsir Hadits"],
            ["id" => 471, "nama" => "Pendidikan Pancasila dan Kewarganegaraan"],
            ["id" => 472, "nama" => "Pendidikan Agama Islam"],
            ["id" => 473, "nama" => "Pendidikan Kepelatihan Olahraga"],
            ["id" => 474, "nama" => "Pendidikan Jasmani Kesehatan dan Rekreasi"],
            ["id" => 475, "nama" => "Pendidikan Ilmu Pengetahuan Alam"],
            ["id" => 476, "nama" => "Pendidikan Bahasa Inggris"],
            ["id" => 477, "nama" => "Pendidikan Bahasa dan Sastra Indonesia"],
            ["id" => 478, "nama" => "Pendidikan Sejarah"],
            ["id" => 479, "nama" => "Pendidikan Matematika"],
            ["id" => 480, "nama" => "Manajemen Pendidikan Islam"],
            ["id" => 481, "nama" => "Pendidikan Geografi"],
            ["id" => 482, "nama" => "Pendidikan Bahasa Arab"],
            ["id" => 483, "nama" => "Pertanian Agronomi dan Hortikultura"],
            ["id" => 484, "nama" => "Mikrobiologi Pertanian"],
            ["id" => 485, "nama" => "Agribisnis (Sosial Ekonomi Pertanian)"],
            ["id" => 486, "nama" => "Agroteknologi"],
            ["id" => 487, "nama" => "Ilmu Kelautan"],
            ["id" => 488, "nama" => "Peternakan"],
            ["id" => 489, "nama" => "Agroeteknologi"],
            ["id" => 490, "nama" => "Kehutanan"],
            ["id" => 491, "nama" => "Budidaya Perairan (Akuakultur)"],
            ["id" => 492, "nama" => "Teknologi Pangan"],
            ["id" => 493, "nama" => "Rekayasa Pertanian"],
            ["id" => 494, "nama" => "Teknologi Pasca Panen"],
            ["id" => 495, "nama" => "Teknologi Hasil Hutan"],
            ["id" => 496, "nama" => "Silvikulutur"],
            ["id" => 497, "nama" => "Konservasi Sumberdaya Hutan dan Ekowisata"],
            ["id" => 498, "nama" => "Ilmu Hama dan Penyakit Tumbuhan (Proteksi Tanaman)"],
            ["id" => 499, "nama" => "Teknologi Industri Pertanian (Agroindustri)"],
            ["id" => 500, "nama" => "Manajemen Sumberdaya Lahan (Ilmu Tanah)"],
            ["id" => 501, "nama" => "Teknologi Hasil Perikanan"],
            ["id" => 502, "nama" => "Agrobisnis Perikanan (Sosial Ekonomi Perikanan)"],
            ["id" => 503, "nama" => "Pengelolaan Hutan"],
            ["id" => 504, "nama" => "Pemanfaatan Sumberdaya Perikanan"],
            ["id" => 505, "nama" => "Teknologi Industri Benih"],
            ["id" => 506, "nama" => "Produksi Ternak"],
            ["id" => 507, "nama" => "Teknologi Hasil Ternak"],
            ["id" => 508, "nama" => "Rekayasa Pertanian"],
            ["id" => 509, "nama" => "Budidaya Perikanan"],
            ["id" => 510, "nama" => "Manajemen Sumber Daya Perairan"],
            ["id" => 511, "nama" => "Manajemen Hutan"],
            ["id" => 512, "nama" => "Penyuluhan dan Komunikasi Pertanian"],
            ["id" => 513, "nama" => "Teknik Pertanian"],
            ["id" => 514, "nama" => "Manajemen Bisnis Unggas"],
            ["id" => 515, "nama" => "Profesi dan Ilmu Terapan Pariwisata"],
            ["id" => 516, "nama" => "Pendidikan Kepolisian"],
            ["id" => 517, "nama" => "Pendidikan Militer"],
            ["id" => 518, "nama" => "Penerbang (Pendidikan Pilot)"],
            ["id" => 519, "nama" => "Pendidikan Intelijen"],
            ["id" => 520, "nama" => "Komunikasi Penerbangan"],
            ["id" => 521, "nama" => "Lalu Lintas Udara"],
            ["id" => 522, "nama" => "Manajemen Logistik"],
            ["id" => 523, "nama" => "Seni Desain Interior"],
            ["id" => 524, "nama" => "Desain Produk"],
            ["id" => 525, "nama" => "Furniture Design"],
            ["id" => 526, "nama" => "Tata Boga"],
            ["id" => 527, "nama" => "Desain Grafis"],
            ["id" => 528, "nama" => "Animasi"],
            ["id" => 529, "nama" => "DKV New Media"],
            ["id" => 530, "nama" => "DKV Creative Advertising"],
            ["id" => 531, "nama" => "Teknik Teknik Pertambangan"],
            ["id" => 532, "nama" => "Teknik Kelautan"],
            ["id" => 533, "nama" => "Teknik Lingkungan"],
            ["id" => 534, "nama" => "Teknik Metalurgi"],
            ["id" => 535, "nama" => "Teknik Sipil"],
            ["id" => 536, "nama" => "Arsitektur"],
            ["id" => 537, "nama" => "Teknik Geodesi"],
            ["id" => 538, "nama" => "Teknik Elektro"],
            ["id" => 539, "nama" => "Teknik Mesin"],
            ["id" => 540, "nama" => "Teknik Industri"],
            ["id" => 541, "nama" => "Teknik Perkapalan"],
            ["id" => 542, "nama" => "Teknik Perencanaan Wilayah dan Kota (Planologi)"],
            ["id" => 543, "nama" => "Teknik Penerbangan (Aeronautika dan Astronautika)"],
            ["id" => 544, "nama" => "Oseanografi"],
            ["id" => 545, "nama" => "Teknik Nuklir"],
            ["id" => 546, "nama" => "Teknik Geologi"],
            ["id" => 547, "nama" => "Teknik Otomotif"],
            ["id" => 548, "nama" => "Teknobiomedik"],
            ["id" => 549, "nama" => "Teknik Perancangan Jalan dan Jembatan"],
            ["id" => 550, "nama" => "Teknik Refrigerasi dan Tata Udara"],
            ["id" => 551, "nama" => "Teknik Telekomunikasi"],
            ["id" => 552, "nama" => "Teknologi Bioproses"],
            ["id" => 553, "nama" => "Teknik Grafika"],
            ["id" => 554, "nama" => "Transportasi Laut"],
            ["id" => 555, "nama" => "Teknik Otomasi Manufaktur dan Mekatronika"],
            ["id" => 556, "nama" => "Rekayasa hayati"],
            ["id" => 557, "nama" => "Teknik Material"],
            ["id" => 558, "nama" => "Automotive and Robotics Engineering"],
            ["id" => 559, "nama" => "Teknik Tenaga Listrik"],
            ["id" => 560, "nama" => "Teknik Sistem Komputer"],
            ["id" => 561, "nama" => "Manajemen Rekayasa Industri"],
            ["id" => 562, "nama" => "Teknik Bioenergi dan Kemurgi"],
            ["id" => 563, "nama" => "Industrial RoboticsDesign"],
            ["id" => 564, "nama" => "Teknik Kimia"],
            ["id" => 565, "nama" => "Teknik Fisika"],
            ["id" => 566, "nama" => "Teknik Geomatika"],
            ["id" => 567, "nama" => "Teknik Perminyakan"],
            ["id" => 568, "nama" => "Teknik Alat Berat"],
            ["id" => 569, "nama" => "Rekayasa Infrastruktur Lingkungan"],
            ["id" => 570, "nama" => "Teknik Pesawat Udara"],
            ["id" => 571, "nama" => "Teknik Telekomunikasi dan Navigasi Udara"],
            ["id" => 572, "nama" => "Teknik Bangunan dan Landasan"],
            ["id" => 573, "nama" => "Teknik Listrik Bandara"],
            ["id" => 574, "nama" => "Teknik Ekonomi Konstruksi (Quantity Surveyor)"],
            ["id" => 575, "nama" => "Teknik Sistem Perkapalan"],
            ["id" => 576, "nama" => "Teknik Pengairan (Sumber Daya Air)"],
            ["id" => 577, "nama" => "Meteorologi Terapan"],
            ["id" => 578, "nama" => "Arsitektur Lanskap"],
            ["id" => 579, "nama" => "Teknik Konversi Energi"],
            ["id" => 580, "nama" => "Teknik Perpipaan"],
            ["id" => 581, "nama" => "MA - Bahasa"],
            ["id" => 582, "nama" => "SMA - Bahasa"],
        ];

        foreach ($program_studi as $studi) {
            Programstudi::create([
                "nama" => $studi["nama"]
            ]);
        }
    }
}
