<?php

namespace Database\Seeders\Wilayah;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('bpr1_kabupaten')
            ->insert([
                ["kode_kabupaten" => "1101","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1102","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH TENGGARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1103","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1104","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "1105","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1106","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH BESAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1107","provinsi_id" => "1","nama_kabupaten" => "KAB. PIDIE","wilayah_id" => "1"],
                ["kode_kabupaten" => "1108","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1109","provinsi_id" => "1","nama_kabupaten" => "KAB. SIMEULUE","wilayah_id" => "1"],
                ["kode_kabupaten" => "1110","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH SINGKIL","wilayah_id" => "1"],
                ["kode_kabupaten" => "1111","provinsi_id" => "1","nama_kabupaten" => "KAB. BIREUEN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1112","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH BARAT DAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1113","provinsi_id" => "1","nama_kabupaten" => "KAB. GAYO LUES","wilayah_id" => "1"],
                ["kode_kabupaten" => "1114","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH JAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1115","provinsi_id" => "1","nama_kabupaten" => "KAB. NAGAN RAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1116","provinsi_id" => "1","nama_kabupaten" => "KAB. ACEH TAMIANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1117","provinsi_id" => "1","nama_kabupaten" => "KAB. BENER MERIAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "1118","provinsi_id" => "1","nama_kabupaten" => "KAB. PIDIE JAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1171","provinsi_id" => "1","nama_kabupaten" => "KOTA BANDA ACEH","wilayah_id" => "2"],
                ["kode_kabupaten" => "1172","provinsi_id" => "1","nama_kabupaten" => "KOTA SABANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "1173","provinsi_id" => "1","nama_kabupaten" => "KOTA LHOKSEUMAWE","wilayah_id" => "2"],
                ["kode_kabupaten" => "1174","provinsi_id" => "1","nama_kabupaten" => "KOTA LANGSA","wilayah_id" => "2"],
                ["kode_kabupaten" => "1175","provinsi_id" => "1","nama_kabupaten" => "KOTA SUBULUSSALAM","wilayah_id" => "2"],
                ["kode_kabupaten" => "1201","provinsi_id" => "2","nama_kabupaten" => "KAB. TAPANULI TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "1202","provinsi_id" => "2","nama_kabupaten" => "KAB. TAPANULI UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1203","provinsi_id" => "2","nama_kabupaten" => "KAB. TAPANULI SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1204","provinsi_id" => "2","nama_kabupaten" => "KAB. NIAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "1205","provinsi_id" => "2","nama_kabupaten" => "KAB. LANGKAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1206","provinsi_id" => "2","nama_kabupaten" => "KAB. KARO","wilayah_id" => "1"],
                ["kode_kabupaten" => "1207","provinsi_id" => "2","nama_kabupaten" => "KAB. DELI SERDANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1208","provinsi_id" => "2","nama_kabupaten" => "KAB. SIMALUNGUN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1209","provinsi_id" => "2","nama_kabupaten" => "KAB. ASAHAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1210","provinsi_id" => "2","nama_kabupaten" => "KAB. LABUHANBATU","wilayah_id" => "1"],
                ["kode_kabupaten" => "1211","provinsi_id" => "2","nama_kabupaten" => "KAB. DAIRI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1212","provinsi_id" => "2","nama_kabupaten" => "KAB. TOBA SAMOSIR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1213","provinsi_id" => "2","nama_kabupaten" => "KAB. MANDAILING NATAL","wilayah_id" => "1"],
                ["kode_kabupaten" => "1214","provinsi_id" => "2","nama_kabupaten" => "KAB. NIAS SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1215","provinsi_id" => "2","nama_kabupaten" => "KAB. PAKPAK BHARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1216","provinsi_id" => "2","nama_kabupaten" => "KAB. HUMBANG HASUNDUTAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1217","provinsi_id" => "2","nama_kabupaten" => "KAB. SAMOSIR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1218","provinsi_id" => "2","nama_kabupaten" => "KAB. SERDANG BEDAGAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1219","provinsi_id" => "2","nama_kabupaten" => "KAB. BATU BARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1220","provinsi_id" => "2","nama_kabupaten" => "KAB. PADANG LAWAS UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1221","provinsi_id" => "2","nama_kabupaten" => "KAB. PADANG LAWAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "1222","provinsi_id" => "2","nama_kabupaten" => "KAB. LABUHANBATU SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1223","provinsi_id" => "2","nama_kabupaten" => "KAB. LABUHANBATU UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1224","provinsi_id" => "2","nama_kabupaten" => "KAB. NIAS UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1225","provinsi_id" => "2","nama_kabupaten" => "KAB. NIAS BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1271","provinsi_id" => "2","nama_kabupaten" => "KOTA MEDAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "1272","provinsi_id" => "2","nama_kabupaten" => "KOTA PEMATANG SIANTAR","wilayah_id" => "2"],
                ["kode_kabupaten" => "1273","provinsi_id" => "2","nama_kabupaten" => "KOTA SIBOLGA","wilayah_id" => "2"],
                ["kode_kabupaten" => "1274","provinsi_id" => "2","nama_kabupaten" => "KOTA TANJUNG BALAI","wilayah_id" => "2"],
                ["kode_kabupaten" => "1275","provinsi_id" => "2","nama_kabupaten" => "KOTA BINJAI","wilayah_id" => "2"],
                ["kode_kabupaten" => "1276","provinsi_id" => "2","nama_kabupaten" => "KOTA TEBING TINGGI","wilayah_id" => "2"],
                ["kode_kabupaten" => "1277","provinsi_id" => "2","nama_kabupaten" => "KOTA PADANGSIDIMPUAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "1278","provinsi_id" => "2","nama_kabupaten" => "KOTA GUNUNGSITOLI","wilayah_id" => "2"],
                ["kode_kabupaten" => "1301","provinsi_id" => "3","nama_kabupaten" => "KAB. PESISIR SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1302","provinsi_id" => "3","nama_kabupaten" => "KAB. SOLOK","wilayah_id" => "1"],
                ["kode_kabupaten" => "1303","provinsi_id" => "3","nama_kabupaten" => "KAB. SIJUNJUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1304","provinsi_id" => "3","nama_kabupaten" => "KAB. TANAH DATAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1305","provinsi_id" => "3","nama_kabupaten" => "KAB. PADANG PARIAMAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1306","provinsi_id" => "3","nama_kabupaten" => "KAB. AGAM","wilayah_id" => "1"],
                ["kode_kabupaten" => "1307","provinsi_id" => "3","nama_kabupaten" => "KAB. LIMA PULUH KOTA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1308","provinsi_id" => "3","nama_kabupaten" => "KAB. PASAMAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1309","provinsi_id" => "3","nama_kabupaten" => "KAB. KEPULAUAN MENTAWAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1310","provinsi_id" => "3","nama_kabupaten" => "KAB. DHARMASRAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1311","provinsi_id" => "3","nama_kabupaten" => "KAB. SOLOK SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1312","provinsi_id" => "3","nama_kabupaten" => "KAB. PASAMAN BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1371","provinsi_id" => "3","nama_kabupaten" => "KOTA PADANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "1372","provinsi_id" => "3","nama_kabupaten" => "KOTA SOLOK","wilayah_id" => "2"],
                ["kode_kabupaten" => "1373","provinsi_id" => "3","nama_kabupaten" => "KOTA SAWAHLUNTO","wilayah_id" => "2"],
                ["kode_kabupaten" => "1374","provinsi_id" => "3","nama_kabupaten" => "KOTA PADANG PANJANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "1375","provinsi_id" => "3","nama_kabupaten" => "KOTA BUKITTINGGI","wilayah_id" => "2"],
                ["kode_kabupaten" => "1376","provinsi_id" => "3","nama_kabupaten" => "KOTA PAYAKUMBUH","wilayah_id" => "2"],
                ["kode_kabupaten" => "1377","provinsi_id" => "3","nama_kabupaten" => "KOTA PARIAMAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "1401","provinsi_id" => "4","nama_kabupaten" => "KAB. KAMPAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1402","provinsi_id" => "4","nama_kabupaten" => "KAB. INDRAGIRI HULU","wilayah_id" => "1"],
                ["kode_kabupaten" => "1403","provinsi_id" => "4","nama_kabupaten" => "KAB. BENGKALIS","wilayah_id" => "1"],
                ["kode_kabupaten" => "1404","provinsi_id" => "4","nama_kabupaten" => "KAB. INDRAGIRI HILIR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1405","provinsi_id" => "4","nama_kabupaten" => "KAB. PELALAWAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1406","provinsi_id" => "4","nama_kabupaten" => "KAB. ROKAN HULU","wilayah_id" => "1"],
                ["kode_kabupaten" => "1407","provinsi_id" => "4","nama_kabupaten" => "KAB. ROKAN HILIR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1408","provinsi_id" => "4","nama_kabupaten" => "KAB. SIAK","wilayah_id" => "1"],
                ["kode_kabupaten" => "1409","provinsi_id" => "4","nama_kabupaten" => "KAB. KUANTAN SINGINGI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1410","provinsi_id" => "4","nama_kabupaten" => "KAB. KEPULAUAN MERANTI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1471","provinsi_id" => "4","nama_kabupaten" => "KOTA PEKANBARU","wilayah_id" => "2"],
                ["kode_kabupaten" => "1472","provinsi_id" => "4","nama_kabupaten" => "KOTA DUMAI","wilayah_id" => "2"],
                ["kode_kabupaten" => "1501","provinsi_id" => "5","nama_kabupaten" => "KAB. KERINCI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1502","provinsi_id" => "5","nama_kabupaten" => "KAB. MERANGIN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1503","provinsi_id" => "5","nama_kabupaten" => "KAB. SAROLANGUN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1504","provinsi_id" => "5","nama_kabupaten" => "KAB. BATANGHARI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1505","provinsi_id" => "5","nama_kabupaten" => "KAB. MUARO JAMBI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1506","provinsi_id" => "5","nama_kabupaten" => "KAB. TANJUNG JABUNG BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1507","provinsi_id" => "5","nama_kabupaten" => "KAB. TANJUNG JABUNG TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1508","provinsi_id" => "5","nama_kabupaten" => "KAB. BUNGO","wilayah_id" => "1"],
                ["kode_kabupaten" => "1509","provinsi_id" => "5","nama_kabupaten" => "KAB. TEBO","wilayah_id" => "1"],
                ["kode_kabupaten" => "1571","provinsi_id" => "5","nama_kabupaten" => "KOTA JAMBI","wilayah_id" => "2"],
                ["kode_kabupaten" => "1572","provinsi_id" => "5","nama_kabupaten" => "KOTA SUNGAI PENUH","wilayah_id" => "2"],
                ["kode_kabupaten" => "1601","provinsi_id" => "6","nama_kabupaten" => "KAB. OGAN KOMERING ULU","wilayah_id" => "1"],
                ["kode_kabupaten" => "1602","provinsi_id" => "6","nama_kabupaten" => "KAB. OGAN KOMERING ILIR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1603","provinsi_id" => "6","nama_kabupaten" => "KAB. MUARA ENIM","wilayah_id" => "1"],
                ["kode_kabupaten" => "1604","provinsi_id" => "6","nama_kabupaten" => "KAB. LAHAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1605","provinsi_id" => "6","nama_kabupaten" => "KAB. MUSI RAWAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "1606","provinsi_id" => "6","nama_kabupaten" => "KAB. MUSI BANYUASIN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1607","provinsi_id" => "6","nama_kabupaten" => "KAB. BANYUASIN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1608","provinsi_id" => "6","nama_kabupaten" => "KAB. OGAN KOMERING ULU TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1609","provinsi_id" => "6","nama_kabupaten" => "KAB. OGAN KOMERING ULU SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1610","provinsi_id" => "6","nama_kabupaten" => "KAB. OGAN ILIR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1611","provinsi_id" => "6","nama_kabupaten" => "KAB. EMPAT LAWANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1612","provinsi_id" => "6","nama_kabupaten" => "KAB. PENUKAL ABAB LEMATANG ILIR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1613","provinsi_id" => "6","nama_kabupaten" => "KAB. MUSI RAWAS UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1671","provinsi_id" => "6","nama_kabupaten" => "KOTA PALEMBANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "1672","provinsi_id" => "6","nama_kabupaten" => "KOTA PAGAR ALAM","wilayah_id" => "2"],
                ["kode_kabupaten" => "1673","provinsi_id" => "6","nama_kabupaten" => "KOTA LUBUK LINGGAU","wilayah_id" => "2"],
                ["kode_kabupaten" => "1674","provinsi_id" => "6","nama_kabupaten" => "KOTA PRABUMULIH","wilayah_id" => "2"],
                ["kode_kabupaten" => "1701","provinsi_id" => "7","nama_kabupaten" => "KAB. BENGKULU SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1702","provinsi_id" => "7","nama_kabupaten" => "KAB. REJANG LEBONG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1703","provinsi_id" => "7","nama_kabupaten" => "KAB. BENGKULU UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1704","provinsi_id" => "7","nama_kabupaten" => "KAB. KAUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1705","provinsi_id" => "7","nama_kabupaten" => "KAB. SELUMA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1706","provinsi_id" => "7","nama_kabupaten" => "KAB. MUKO MUKO","wilayah_id" => "1"],
                ["kode_kabupaten" => "1707","provinsi_id" => "7","nama_kabupaten" => "KAB. LEBONG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1708","provinsi_id" => "7","nama_kabupaten" => "KAB. KEPAHIANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1709","provinsi_id" => "7","nama_kabupaten" => "KAB. BENGKULU TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "1771","provinsi_id" => "7","nama_kabupaten" => "KOTA BENGKULU","wilayah_id" => "2"],
                ["kode_kabupaten" => "1801","provinsi_id" => "8","nama_kabupaten" => "KAB. LAMPUNG SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1802","provinsi_id" => "8","nama_kabupaten" => "KAB. LAMPUNG TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "1803","provinsi_id" => "8","nama_kabupaten" => "KAB. LAMPUNG UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1804","provinsi_id" => "8","nama_kabupaten" => "KAB. LAMPUNG BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1805","provinsi_id" => "8","nama_kabupaten" => "KAB. TULANG BAWANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1806","provinsi_id" => "8","nama_kabupaten" => "KAB. TANGGAMUS","wilayah_id" => "1"],
                ["kode_kabupaten" => "1807","provinsi_id" => "8","nama_kabupaten" => "KAB. LAMPUNG TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1808","provinsi_id" => "8","nama_kabupaten" => "KAB. WAY KANAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1809","provinsi_id" => "8","nama_kabupaten" => "KAB. PESAWARAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1810","provinsi_id" => "8","nama_kabupaten" => "KAB. PRINGSEWU","wilayah_id" => "1"],
                ["kode_kabupaten" => "1811","provinsi_id" => "8","nama_kabupaten" => "KAB. MESUJI","wilayah_id" => "1"],
                ["kode_kabupaten" => "1812","provinsi_id" => "8","nama_kabupaten" => "KAB. TULANG BAWANG BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1813","provinsi_id" => "8","nama_kabupaten" => "KAB. PESISIR BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1871","provinsi_id" => "8","nama_kabupaten" => "KOTA BANDAR LAMPUNG","wilayah_id" => "2"],
                ["kode_kabupaten" => "1872","provinsi_id" => "8","nama_kabupaten" => "KOTA METRO","wilayah_id" => "2"],
                ["kode_kabupaten" => "1901","provinsi_id" => "9","nama_kabupaten" => "KAB. BANGKA","wilayah_id" => "1"],
                ["kode_kabupaten" => "1902","provinsi_id" => "9","nama_kabupaten" => "KAB. BELITUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "1903","provinsi_id" => "9","nama_kabupaten" => "KAB. BANGKA SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "1904","provinsi_id" => "9","nama_kabupaten" => "KAB. BANGKA TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "1905","provinsi_id" => "9","nama_kabupaten" => "KAB. BANGKA BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "1906","provinsi_id" => "9","nama_kabupaten" => "KAB. BELITUNG TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "1971","provinsi_id" => "9","nama_kabupaten" => "KOTA PANGKAL PINANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "2101","provinsi_id" => "10","nama_kabupaten" => "KAB. BINTAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "2102","provinsi_id" => "10","nama_kabupaten" => "KAB. KARIMUN","wilayah_id" => "1"],
                ["kode_kabupaten" => "2103","provinsi_id" => "10","nama_kabupaten" => "KAB. NATUNA","wilayah_id" => "1"],
                ["kode_kabupaten" => "2104","provinsi_id" => "10","nama_kabupaten" => "KAB. LINGGA","wilayah_id" => "1"],
                ["kode_kabupaten" => "2105","provinsi_id" => "10","nama_kabupaten" => "KAB. KEPULAUAN ANAMBAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "2171","provinsi_id" => "10","nama_kabupaten" => "KOTA BATAM","wilayah_id" => "2"],
                ["kode_kabupaten" => "2172","provinsi_id" => "10","nama_kabupaten" => "KOTA TANJUNG PINANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "3101","provinsi_id" => "11","nama_kabupaten" => "KAB. ADM. KEP. SERIBU","wilayah_id" => "1"],
                ["kode_kabupaten" => "3171","provinsi_id" => "11","nama_kabupaten" => "KOTA ADM. JAKARTA PUSAT","wilayah_id" => "2"],
                ["kode_kabupaten" => "3172","provinsi_id" => "11","nama_kabupaten" => "KOTA ADM. JAKARTA UTARA","wilayah_id" => "2"],
                ["kode_kabupaten" => "3173","provinsi_id" => "11","nama_kabupaten" => "KOTA ADM. JAKARTA BARAT","wilayah_id" => "2"],
                ["kode_kabupaten" => "3174","provinsi_id" => "11","nama_kabupaten" => "KOTA ADM. JAKARTA SELATAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "3175","provinsi_id" => "11","nama_kabupaten" => "KOTA ADM. JAKARTA TIMUR","wilayah_id" => "2"],
                ["kode_kabupaten" => "3201","provinsi_id" => "12","nama_kabupaten" => "KAB. BOGOR","wilayah_id" => "1"],
                ["kode_kabupaten" => "3202","provinsi_id" => "12","nama_kabupaten" => "KAB. SUKABUMI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3203","provinsi_id" => "12","nama_kabupaten" => "KAB. CIANJUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "3204","provinsi_id" => "12","nama_kabupaten" => "KAB. BANDUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3205","provinsi_id" => "12","nama_kabupaten" => "KAB. GARUT","wilayah_id" => "1"],
                ["kode_kabupaten" => "3206","provinsi_id" => "12","nama_kabupaten" => "KAB. TASIKMALAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "3207","provinsi_id" => "12","nama_kabupaten" => "KAB. CIAMIS","wilayah_id" => "1"],
                ["kode_kabupaten" => "3208","provinsi_id" => "12","nama_kabupaten" => "KAB. KUNINGAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3209","provinsi_id" => "12","nama_kabupaten" => "KAB. CIREBON","wilayah_id" => "1"],
                ["kode_kabupaten" => "3210","provinsi_id" => "12","nama_kabupaten" => "KAB. MAJALENGKA","wilayah_id" => "1"],
                ["kode_kabupaten" => "3211","provinsi_id" => "12","nama_kabupaten" => "KAB. SUMEDANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3212","provinsi_id" => "12","nama_kabupaten" => "KAB. INDRAMAYU","wilayah_id" => "1"],
                ["kode_kabupaten" => "3213","provinsi_id" => "12","nama_kabupaten" => "KAB. SUBANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3214","provinsi_id" => "12","nama_kabupaten" => "KAB. PURWAKARTA","wilayah_id" => "1"],
                ["kode_kabupaten" => "3215","provinsi_id" => "12","nama_kabupaten" => "KAB. KARAWANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3216","provinsi_id" => "12","nama_kabupaten" => "KAB. BEKASI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3217","provinsi_id" => "12","nama_kabupaten" => "KAB. BANDUNG BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "3218","provinsi_id" => "12","nama_kabupaten" => "KAB. PANGANDARAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3271","provinsi_id" => "12","nama_kabupaten" => "KOTA BOGOR","wilayah_id" => "2"],
                ["kode_kabupaten" => "3272","provinsi_id" => "12","nama_kabupaten" => "KOTA SUKABUMI","wilayah_id" => "2"],
                ["kode_kabupaten" => "3273","provinsi_id" => "12","nama_kabupaten" => "KOTA BANDUNG","wilayah_id" => "2"],
                ["kode_kabupaten" => "3274","provinsi_id" => "12","nama_kabupaten" => "KOTA CIREBON","wilayah_id" => "2"],
                ["kode_kabupaten" => "3275","provinsi_id" => "12","nama_kabupaten" => "KOTA BEKASI","wilayah_id" => "2"],
                ["kode_kabupaten" => "3276","provinsi_id" => "12","nama_kabupaten" => "KOTA DEPOK","wilayah_id" => "2"],
                ["kode_kabupaten" => "3277","provinsi_id" => "12","nama_kabupaten" => "KOTA CIMAHI","wilayah_id" => "2"],
                ["kode_kabupaten" => "3278","provinsi_id" => "12","nama_kabupaten" => "KOTA TASIKMALAYA","wilayah_id" => "2"],
                ["kode_kabupaten" => "3279","provinsi_id" => "12","nama_kabupaten" => "KOTA BANJAR","wilayah_id" => "2"],
                ["kode_kabupaten" => "3301","provinsi_id" => "13","nama_kabupaten" => "KAB. CILACAP","wilayah_id" => "1"],
                ["kode_kabupaten" => "3302","provinsi_id" => "13","nama_kabupaten" => "KAB. BANYUMAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "3303","provinsi_id" => "13","nama_kabupaten" => "KAB. PURBALINGGA","wilayah_id" => "1"],
                ["kode_kabupaten" => "3304","provinsi_id" => "13","nama_kabupaten" => "KAB. BANJARNEGARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "3305","provinsi_id" => "13","nama_kabupaten" => "KAB. KEBUMEN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3306","provinsi_id" => "13","nama_kabupaten" => "KAB. PURWOREJO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3307","provinsi_id" => "13","nama_kabupaten" => "KAB. WONOSOBO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3308","provinsi_id" => "13","nama_kabupaten" => "KAB. MAGELANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3309","provinsi_id" => "13","nama_kabupaten" => "KAB. BOYOLALI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3310","provinsi_id" => "13","nama_kabupaten" => "KAB. KLATEN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3311","provinsi_id" => "13","nama_kabupaten" => "KAB. SUKOHARJO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3312","provinsi_id" => "13","nama_kabupaten" => "KAB. WONOGIRI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3313","provinsi_id" => "13","nama_kabupaten" => "KAB. KARANGANYAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "3314","provinsi_id" => "13","nama_kabupaten" => "KAB. SRAGEN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3315","provinsi_id" => "13","nama_kabupaten" => "KAB. GROBOGAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3316","provinsi_id" => "13","nama_kabupaten" => "KAB. BLORA","wilayah_id" => "1"],
                ["kode_kabupaten" => "3317","provinsi_id" => "13","nama_kabupaten" => "KAB. REMBANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3318","provinsi_id" => "13","nama_kabupaten" => "KAB. PATI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3319","provinsi_id" => "13","nama_kabupaten" => "KAB. KUDUS","wilayah_id" => "1"],
                ["kode_kabupaten" => "3320","provinsi_id" => "13","nama_kabupaten" => "KAB. JEPARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "3321","provinsi_id" => "13","nama_kabupaten" => "KAB. DEMAK","wilayah_id" => "1"],
                ["kode_kabupaten" => "3322","provinsi_id" => "13","nama_kabupaten" => "KAB. SEMARANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3323","provinsi_id" => "13","nama_kabupaten" => "KAB. TEMANGGUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3324","provinsi_id" => "13","nama_kabupaten" => "KAB. KENDAL","wilayah_id" => "1"],
                ["kode_kabupaten" => "3325","provinsi_id" => "13","nama_kabupaten" => "KAB. BATANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3326","provinsi_id" => "13","nama_kabupaten" => "KAB. PEKALONGAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3327","provinsi_id" => "13","nama_kabupaten" => "KAB. PEMALANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3328","provinsi_id" => "13","nama_kabupaten" => "KAB. TEGAL","wilayah_id" => "1"],
                ["kode_kabupaten" => "3329","provinsi_id" => "13","nama_kabupaten" => "KAB. BREBES","wilayah_id" => "1"],
                ["kode_kabupaten" => "3371","provinsi_id" => "13","nama_kabupaten" => "KOTA MAGELANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "3372","provinsi_id" => "13","nama_kabupaten" => "KOTA SURAKARTA","wilayah_id" => "2"],
                ["kode_kabupaten" => "3373","provinsi_id" => "13","nama_kabupaten" => "KOTA SALATIGA","wilayah_id" => "2"],
                ["kode_kabupaten" => "3374","provinsi_id" => "13","nama_kabupaten" => "KOTA SEMARANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "3375","provinsi_id" => "13","nama_kabupaten" => "KOTA PEKALONGAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "3376","provinsi_id" => "13","nama_kabupaten" => "KOTA TEGAL","wilayah_id" => "2"],
                ["kode_kabupaten" => "3401","provinsi_id" => "14","nama_kabupaten" => "KAB. KULON PROGO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3402","provinsi_id" => "14","nama_kabupaten" => "KAB. BANTUL","wilayah_id" => "1"],
                ["kode_kabupaten" => "3403","provinsi_id" => "14","nama_kabupaten" => "KAB. GUNUNG KIDUL","wilayah_id" => "1"],
                ["kode_kabupaten" => "3404","provinsi_id" => "14","nama_kabupaten" => "KAB. SLEMAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3471","provinsi_id" => "14","nama_kabupaten" => "KOTA YOGYAKARTA","wilayah_id" => "2"],
                ["kode_kabupaten" => "3501","provinsi_id" => "15","nama_kabupaten" => "KAB. PACITAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3502","provinsi_id" => "15","nama_kabupaten" => "KAB. PONOROGO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3503","provinsi_id" => "15","nama_kabupaten" => "KAB. TRENGGALEK","wilayah_id" => "1"],
                ["kode_kabupaten" => "3504","provinsi_id" => "15","nama_kabupaten" => "KAB. TULUNGAGUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3505","provinsi_id" => "15","nama_kabupaten" => "KAB. BLITAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "3506","provinsi_id" => "15","nama_kabupaten" => "KAB. KEDIRI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3507","provinsi_id" => "15","nama_kabupaten" => "KAB. MALANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3508","provinsi_id" => "15","nama_kabupaten" => "KAB. LUMAJANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3509","provinsi_id" => "15","nama_kabupaten" => "KAB. JEMBER","wilayah_id" => "1"],
                ["kode_kabupaten" => "3510","provinsi_id" => "15","nama_kabupaten" => "KAB. BANYUWANGI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3511","provinsi_id" => "15","nama_kabupaten" => "KAB. BONDOWOSO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3512","provinsi_id" => "15","nama_kabupaten" => "KAB. SITUBONDO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3513","provinsi_id" => "15","nama_kabupaten" => "KAB. PROBOLINGGO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3514","provinsi_id" => "15","nama_kabupaten" => "KAB. PASURUAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3515","provinsi_id" => "15","nama_kabupaten" => "KAB. SIDOARJO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3516","provinsi_id" => "15","nama_kabupaten" => "KAB. MOJOKERTO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3517","provinsi_id" => "15","nama_kabupaten" => "KAB. JOMBANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3518","provinsi_id" => "15","nama_kabupaten" => "KAB. NGANJUK","wilayah_id" => "1"],
                ["kode_kabupaten" => "3519","provinsi_id" => "15","nama_kabupaten" => "KAB. MADIUN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3520","provinsi_id" => "15","nama_kabupaten" => "KAB. MAGETAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3521","provinsi_id" => "15","nama_kabupaten" => "KAB. NGAWI","wilayah_id" => "1"],
                ["kode_kabupaten" => "3522","provinsi_id" => "15","nama_kabupaten" => "KAB. BOJONEGORO","wilayah_id" => "1"],
                ["kode_kabupaten" => "3523","provinsi_id" => "15","nama_kabupaten" => "KAB. TUBAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3524","provinsi_id" => "15","nama_kabupaten" => "KAB. LAMONGAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3525","provinsi_id" => "15","nama_kabupaten" => "KAB. GRESIK","wilayah_id" => "1"],
                ["kode_kabupaten" => "3526","provinsi_id" => "15","nama_kabupaten" => "KAB. BANGKALAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3527","provinsi_id" => "15","nama_kabupaten" => "KAB. SAMPANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3528","provinsi_id" => "15","nama_kabupaten" => "KAB. PAMEKASAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "3529","provinsi_id" => "15","nama_kabupaten" => "KAB. SUMENEP","wilayah_id" => "1"],
                ["kode_kabupaten" => "3571","provinsi_id" => "15","nama_kabupaten" => "KOTA KEDIRI","wilayah_id" => "2"],
                ["kode_kabupaten" => "3572","provinsi_id" => "15","nama_kabupaten" => "KOTA BLITAR","wilayah_id" => "2"],
                ["kode_kabupaten" => "3573","provinsi_id" => "15","nama_kabupaten" => "KOTA MALANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "3574","provinsi_id" => "15","nama_kabupaten" => "KOTA PROBOLINGGO","wilayah_id" => "2"],
                ["kode_kabupaten" => "3575","provinsi_id" => "15","nama_kabupaten" => "KOTA PASURUAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "3576","provinsi_id" => "15","nama_kabupaten" => "KOTA MOJOKERTO","wilayah_id" => "2"],
                ["kode_kabupaten" => "3577","provinsi_id" => "15","nama_kabupaten" => "KOTA MADIUN","wilayah_id" => "2"],
                ["kode_kabupaten" => "3578","provinsi_id" => "15","nama_kabupaten" => "KOTA SURABAYA","wilayah_id" => "2"],
                ["kode_kabupaten" => "3579","provinsi_id" => "15","nama_kabupaten" => "KOTA BATU","wilayah_id" => "2"],
                ["kode_kabupaten" => "3601","provinsi_id" => "16","nama_kabupaten" => "KAB. PANDEGLANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3602","provinsi_id" => "16","nama_kabupaten" => "KAB. LEBAK","wilayah_id" => "1"],
                ["kode_kabupaten" => "3603","provinsi_id" => "16","nama_kabupaten" => "KAB. TANGERANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3604","provinsi_id" => "16","nama_kabupaten" => "KAB. SERANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "3671","provinsi_id" => "16","nama_kabupaten" => "KOTA TANGERANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "3672","provinsi_id" => "16","nama_kabupaten" => "KOTA CILEGON","wilayah_id" => "2"],
                ["kode_kabupaten" => "3673","provinsi_id" => "16","nama_kabupaten" => "KOTA SERANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "3674","provinsi_id" => "16","nama_kabupaten" => "KOTA TANGERANG SELATAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "5101","provinsi_id" => "17","nama_kabupaten" => "KAB. JEMBRANA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5102","provinsi_id" => "17","nama_kabupaten" => "KAB. TABANAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "5103","provinsi_id" => "17","nama_kabupaten" => "KAB. BADUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "5104","provinsi_id" => "17","nama_kabupaten" => "KAB. GIANYAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "5105","provinsi_id" => "17","nama_kabupaten" => "KAB. KLUNGKUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "5106","provinsi_id" => "17","nama_kabupaten" => "KAB. BANGLI","wilayah_id" => "1"],
                ["kode_kabupaten" => "5107","provinsi_id" => "17","nama_kabupaten" => "KAB. KARANGASEM","wilayah_id" => "1"],
                ["kode_kabupaten" => "5108","provinsi_id" => "17","nama_kabupaten" => "KAB. BULELENG","wilayah_id" => "1"],
                ["kode_kabupaten" => "5171","provinsi_id" => "17","nama_kabupaten" => "KOTA DENPASAR","wilayah_id" => "2"],
                ["kode_kabupaten" => "5201","provinsi_id" => "18","nama_kabupaten" => "KAB. LOMBOK BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "5202","provinsi_id" => "18","nama_kabupaten" => "KAB. LOMBOK TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "5203","provinsi_id" => "18","nama_kabupaten" => "KAB. LOMBOK TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "5204","provinsi_id" => "18","nama_kabupaten" => "KAB. SUMBAWA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5205","provinsi_id" => "18","nama_kabupaten" => "KAB. DOMPU","wilayah_id" => "1"],
                ["kode_kabupaten" => "5206","provinsi_id" => "18","nama_kabupaten" => "KAB. BIMA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5207","provinsi_id" => "18","nama_kabupaten" => "KAB. SUMBAWA BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "5208","provinsi_id" => "18","nama_kabupaten" => "KAB. LOMBOK UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5271","provinsi_id" => "18","nama_kabupaten" => "KOTA MATARAM","wilayah_id" => "2"],
                ["kode_kabupaten" => "5272","provinsi_id" => "18","nama_kabupaten" => "KOTA BIMA","wilayah_id" => "2"],
                ["kode_kabupaten" => "5301","provinsi_id" => "19","nama_kabupaten" => "KAB. KUPANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "5302","provinsi_id" => "19","nama_kabupaten" => "KAB TIMOR TENGAH SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "5303","provinsi_id" => "19","nama_kabupaten" => "KAB. TIMOR TENGAH UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5304","provinsi_id" => "19","nama_kabupaten" => "KAB. BELU","wilayah_id" => "1"],
                ["kode_kabupaten" => "5305","provinsi_id" => "19","nama_kabupaten" => "KAB. ALOR","wilayah_id" => "1"],
                ["kode_kabupaten" => "5306","provinsi_id" => "19","nama_kabupaten" => "KAB. FLORES TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "5307","provinsi_id" => "19","nama_kabupaten" => "KAB. SIKKA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5308","provinsi_id" => "19","nama_kabupaten" => "KAB. ENDE","wilayah_id" => "1"],
                ["kode_kabupaten" => "5309","provinsi_id" => "19","nama_kabupaten" => "KAB. NGADA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5310","provinsi_id" => "19","nama_kabupaten" => "KAB. MANGGARAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "5311","provinsi_id" => "19","nama_kabupaten" => "KAB. SUMBA TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "5312","provinsi_id" => "19","nama_kabupaten" => "KAB. SUMBA BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "5313","provinsi_id" => "19","nama_kabupaten" => "KAB. LEMBATA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5314","provinsi_id" => "19","nama_kabupaten" => "KAB. ROTE NDAO","wilayah_id" => "1"],
                ["kode_kabupaten" => "5315","provinsi_id" => "19","nama_kabupaten" => "KAB. MANGGARAI BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "5316","provinsi_id" => "19","nama_kabupaten" => "KAB. NAGEKEO","wilayah_id" => "1"],
                ["kode_kabupaten" => "5317","provinsi_id" => "19","nama_kabupaten" => "KAB. SUMBA TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "5318","provinsi_id" => "19","nama_kabupaten" => "KAB. SUMBA BARAT DAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5319","provinsi_id" => "19","nama_kabupaten" => "KAB. MANGGARAI TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "5320","provinsi_id" => "19","nama_kabupaten" => "KAB. SABU RAIJUA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5321","provinsi_id" => "19","nama_kabupaten" => "KAB. MALAKA","wilayah_id" => "1"],
                ["kode_kabupaten" => "5371","provinsi_id" => "19","nama_kabupaten" => "KOTA KUPANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "6101","provinsi_id" => "20","nama_kabupaten" => "KAB. SAMBAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "6102","provinsi_id" => "20","nama_kabupaten" => "KAB. MEMPAWAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "6103","provinsi_id" => "20","nama_kabupaten" => "KAB. SANGGAU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6104","provinsi_id" => "20","nama_kabupaten" => "KAB. KETAPANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "6105","provinsi_id" => "20","nama_kabupaten" => "KAB. SINTANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "6106","provinsi_id" => "20","nama_kabupaten" => "KAB. KAPUAS HULU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6107","provinsi_id" => "20","nama_kabupaten" => "KAB. BENGKAYANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "6108","provinsi_id" => "20","nama_kabupaten" => "KAB. LANDAK","wilayah_id" => "1"],
                ["kode_kabupaten" => "6109","provinsi_id" => "20","nama_kabupaten" => "KAB. SEKADAU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6110","provinsi_id" => "20","nama_kabupaten" => "KAB. MELAWI","wilayah_id" => "1"],
                ["kode_kabupaten" => "6111","provinsi_id" => "20","nama_kabupaten" => "KAB. KAYONG UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6112","provinsi_id" => "20","nama_kabupaten" => "KAB. KUBU RAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6171","provinsi_id" => "20","nama_kabupaten" => "KOTA PONTIANAK","wilayah_id" => "2"],
                ["kode_kabupaten" => "6172","provinsi_id" => "20","nama_kabupaten" => "KOTA SINGKAWANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "6201","provinsi_id" => "21","nama_kabupaten" => "KAB. KOTAWARINGIN BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "6202","provinsi_id" => "21","nama_kabupaten" => "KAB. KOTAWARINGIN TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "6203","provinsi_id" => "21","nama_kabupaten" => "KAB. KAPUAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "6204","provinsi_id" => "21","nama_kabupaten" => "KAB. BARITO SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6205","provinsi_id" => "21","nama_kabupaten" => "KAB. BARITO UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6206","provinsi_id" => "21","nama_kabupaten" => "KAB. KATINGAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6207","provinsi_id" => "21","nama_kabupaten" => "KAB. SERUYAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6208","provinsi_id" => "21","nama_kabupaten" => "KAB. SUKAMARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6209","provinsi_id" => "21","nama_kabupaten" => "KAB. LAMANDAU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6210","provinsi_id" => "21","nama_kabupaten" => "KAB. GUNUNG MAS","wilayah_id" => "1"],
                ["kode_kabupaten" => "6211","provinsi_id" => "21","nama_kabupaten" => "KAB. PULANG PISAU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6212","provinsi_id" => "21","nama_kabupaten" => "KAB. MURUNG RAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6213","provinsi_id" => "21","nama_kabupaten" => "KAB. BARITO TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "6271","provinsi_id" => "21","nama_kabupaten" => "KOTA PALANGKARAYA","wilayah_id" => "2"],
                ["kode_kabupaten" => "6301","provinsi_id" => "22","nama_kabupaten" => "KAB. TANAH LAUT","wilayah_id" => "1"],
                ["kode_kabupaten" => "6302","provinsi_id" => "22","nama_kabupaten" => "KAB. KOTABARU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6303","provinsi_id" => "22","nama_kabupaten" => "KAB. BANJAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "6304","provinsi_id" => "22","nama_kabupaten" => "KAB. BARITO KUALA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6305","provinsi_id" => "22","nama_kabupaten" => "KAB. TAPIN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6306","provinsi_id" => "22","nama_kabupaten" => "KAB. HULU SUNGAI SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6307","provinsi_id" => "22","nama_kabupaten" => "KAB. HULU SUNGAI TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "6308","provinsi_id" => "22","nama_kabupaten" => "KAB. HULU SUNGAI UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6309","provinsi_id" => "22","nama_kabupaten" => "KAB. TABALONG","wilayah_id" => "1"],
                ["kode_kabupaten" => "6310","provinsi_id" => "22","nama_kabupaten" => "KAB. TANAH BUMBU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6311","provinsi_id" => "22","nama_kabupaten" => "KAB. BALANGAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6371","provinsi_id" => "22","nama_kabupaten" => "KOTA BANJARMASIN","wilayah_id" => "2"],
                ["kode_kabupaten" => "6372","provinsi_id" => "22","nama_kabupaten" => "KOTA BANJARBARU","wilayah_id" => "2"],
                ["kode_kabupaten" => "6401","provinsi_id" => "23","nama_kabupaten" => "KAB. PASER","wilayah_id" => "1"],
                ["kode_kabupaten" => "6402","provinsi_id" => "23","nama_kabupaten" => "KAB. KUTAI KARTANEGARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6403","provinsi_id" => "23","nama_kabupaten" => "KAB. BERAU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6407","provinsi_id" => "23","nama_kabupaten" => "KAB. KUTAI BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "6408","provinsi_id" => "23","nama_kabupaten" => "KAB. KUTAI TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "6409","provinsi_id" => "23","nama_kabupaten" => "KAB. PENAJAM PASER UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "6411","provinsi_id" => "23","nama_kabupaten" => "KAB. MAHAKAM ULU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6471","provinsi_id" => "23","nama_kabupaten" => "KOTA BALIKPAPAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "6472","provinsi_id" => "23","nama_kabupaten" => "KOTA SAMARINDA","wilayah_id" => "2"],
                ["kode_kabupaten" => "6474","provinsi_id" => "23","nama_kabupaten" => "KOTA BONTANG","wilayah_id" => "2"],
                ["kode_kabupaten" => "6501","provinsi_id" => "24","nama_kabupaten" => "KAB. BULUNGAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6502","provinsi_id" => "24","nama_kabupaten" => "KAB. MALINAU","wilayah_id" => "1"],
                ["kode_kabupaten" => "6503","provinsi_id" => "24","nama_kabupaten" => "KAB. NUNUKAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "6504","provinsi_id" => "24","nama_kabupaten" => "KAB. TANA TIDUNG","wilayah_id" => "1"],
                ["kode_kabupaten" => "6571","provinsi_id" => "24","nama_kabupaten" => "KOTA TARAKAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "7101","provinsi_id" => "25","nama_kabupaten" => "KAB. BOLAANG MONGONDOW","wilayah_id" => "1"],
                ["kode_kabupaten" => "7102","provinsi_id" => "25","nama_kabupaten" => "KAB. MINAHASA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7103","provinsi_id" => "25","nama_kabupaten" => "KAB. KEPULAUAN SANGIHE","wilayah_id" => "1"],
                ["kode_kabupaten" => "7104","provinsi_id" => "25","nama_kabupaten" => "KAB. KEPULAUAN TALAUD","wilayah_id" => "1"],
                ["kode_kabupaten" => "7105","provinsi_id" => "25","nama_kabupaten" => "KAB. MINAHASA SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "7106","provinsi_id" => "25","nama_kabupaten" => "KAB. MINAHASA UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7107","provinsi_id" => "25","nama_kabupaten" => "KAB. MINAHASA TENGGARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7108","provinsi_id" => "25","nama_kabupaten" => "KAB. BOLAANG MONGONDOW UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7109","provinsi_id" => "25","nama_kabupaten" => "KAB. KEP. SIAU TAGULANDANG BIARO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7110","provinsi_id" => "25","nama_kabupaten" => "KAB. BOLAANG MONGONDOW TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "7111","provinsi_id" => "25","nama_kabupaten" => "KAB. BOLAANG MONGONDOW SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "7171","provinsi_id" => "25","nama_kabupaten" => "KOTA MANADO","wilayah_id" => "2"],
                ["kode_kabupaten" => "7172","provinsi_id" => "25","nama_kabupaten" => "KOTA BITUNG","wilayah_id" => "2"],
                ["kode_kabupaten" => "7173","provinsi_id" => "25","nama_kabupaten" => "KOTA TOMOHON","wilayah_id" => "2"],
                ["kode_kabupaten" => "7174","provinsi_id" => "25","nama_kabupaten" => "KOTA KOTAMOBAGU","wilayah_id" => "2"],
                ["kode_kabupaten" => "7201","provinsi_id" => "26","nama_kabupaten" => "KAB. BANGGAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "7202","provinsi_id" => "26","nama_kabupaten" => "KAB. POSO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7203","provinsi_id" => "26","nama_kabupaten" => "KAB. DONGGALA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7204","provinsi_id" => "26","nama_kabupaten" => "KAB. TOLI TOLI","wilayah_id" => "1"],
                ["kode_kabupaten" => "7205","provinsi_id" => "26","nama_kabupaten" => "KAB. BUOL","wilayah_id" => "1"],
                ["kode_kabupaten" => "7206","provinsi_id" => "26","nama_kabupaten" => "KAB. MOROWALI","wilayah_id" => "1"],
                ["kode_kabupaten" => "7207","provinsi_id" => "26","nama_kabupaten" => "KAB. BANGGAI KEPULAUAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "7208","provinsi_id" => "26","nama_kabupaten" => "KAB. PARIGI MOUTONG","wilayah_id" => "1"],
                ["kode_kabupaten" => "7209","provinsi_id" => "26","nama_kabupaten" => "KAB. TOJO UNA UNA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7210","provinsi_id" => "26","nama_kabupaten" => "KAB. SIGI","wilayah_id" => "1"],
                ["kode_kabupaten" => "7211","provinsi_id" => "26","nama_kabupaten" => "KAB. BANGGAI LAUT","wilayah_id" => "1"],
                ["kode_kabupaten" => "7212","provinsi_id" => "26","nama_kabupaten" => "KAB. MOROWALI UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7271","provinsi_id" => "26","nama_kabupaten" => "KOTA PALU","wilayah_id" => "2"],
                ["kode_kabupaten" => "7301","provinsi_id" => "27","nama_kabupaten" => "KAB. KEPULAUAN SELAYAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "7302","provinsi_id" => "27","nama_kabupaten" => "KAB. BULUKUMBA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7303","provinsi_id" => "27","nama_kabupaten" => "KAB. BANTAENG","wilayah_id" => "1"],
                ["kode_kabupaten" => "7304","provinsi_id" => "27","nama_kabupaten" => "KAB. JENEPONTO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7305","provinsi_id" => "27","nama_kabupaten" => "KAB. TAKALAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "7306","provinsi_id" => "27","nama_kabupaten" => "KAB. GOWA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7307","provinsi_id" => "27","nama_kabupaten" => "KAB. SINJAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "7308","provinsi_id" => "27","nama_kabupaten" => "KAB. BONE","wilayah_id" => "1"],
                ["kode_kabupaten" => "7309","provinsi_id" => "27","nama_kabupaten" => "KAB. MAROS","wilayah_id" => "1"],
                ["kode_kabupaten" => "7310","provinsi_id" => "27","nama_kabupaten" => "KAB. PANGKAJENE KEPULAUAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "7311","provinsi_id" => "27","nama_kabupaten" => "KAB. BARRU","wilayah_id" => "1"],
                ["kode_kabupaten" => "7312","provinsi_id" => "27","nama_kabupaten" => "KAB. SOPPENG","wilayah_id" => "1"],
                ["kode_kabupaten" => "7313","provinsi_id" => "27","nama_kabupaten" => "KAB. WAJO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7314","provinsi_id" => "27","nama_kabupaten" => "KAB. SIDENRENG RAPPANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "7315","provinsi_id" => "27","nama_kabupaten" => "KAB. PINRANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "7316","provinsi_id" => "27","nama_kabupaten" => "KAB. ENREKANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "7317","provinsi_id" => "27","nama_kabupaten" => "KAB. LUWU","wilayah_id" => "1"],
                ["kode_kabupaten" => "7318","provinsi_id" => "27","nama_kabupaten" => "KAB. TANA TORAJA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7322","provinsi_id" => "27","nama_kabupaten" => "KAB. LUWU UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7324","provinsi_id" => "27","nama_kabupaten" => "KAB. LUWU TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "7326","provinsi_id" => "27","nama_kabupaten" => "KAB. TORAJA UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7371","provinsi_id" => "27","nama_kabupaten" => "KOTA MAKASSAR","wilayah_id" => "2"],
                ["kode_kabupaten" => "7372","provinsi_id" => "27","nama_kabupaten" => "KOTA PARE PARE","wilayah_id" => "2"],
                ["kode_kabupaten" => "7373","provinsi_id" => "27","nama_kabupaten" => "KOTA PALOPO","wilayah_id" => "2"],
                ["kode_kabupaten" => "7401","provinsi_id" => "28","nama_kabupaten" => "KAB. KOLAKA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7402","provinsi_id" => "28","nama_kabupaten" => "KAB. KONAWE","wilayah_id" => "1"],
                ["kode_kabupaten" => "7403","provinsi_id" => "28","nama_kabupaten" => "KAB. MUNA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7404","provinsi_id" => "28","nama_kabupaten" => "KAB. BUTON","wilayah_id" => "1"],
                ["kode_kabupaten" => "7405","provinsi_id" => "28","nama_kabupaten" => "KAB. KONAWE SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "7406","provinsi_id" => "28","nama_kabupaten" => "KAB. BOMBANA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7407","provinsi_id" => "28","nama_kabupaten" => "KAB. WAKATOBI","wilayah_id" => "1"],
                ["kode_kabupaten" => "7408","provinsi_id" => "28","nama_kabupaten" => "KAB. KOLAKA UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7409","provinsi_id" => "28","nama_kabupaten" => "KAB. KONAWE UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7410","provinsi_id" => "28","nama_kabupaten" => "KAB. BUTON UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7411","provinsi_id" => "28","nama_kabupaten" => "KAB. KOLAKA TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "7412","provinsi_id" => "28","nama_kabupaten" => "KAB. KONAWE KEPULAUAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "7413","provinsi_id" => "28","nama_kabupaten" => "KAB. MUNA BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "7414","provinsi_id" => "28","nama_kabupaten" => "KAB. BUTON TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "7415","provinsi_id" => "28","nama_kabupaten" => "KAB. BUTON SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "7471","provinsi_id" => "28","nama_kabupaten" => "KOTA KENDARI","wilayah_id" => "2"],
                ["kode_kabupaten" => "7472","provinsi_id" => "28","nama_kabupaten" => "KOTA BAU BAU","wilayah_id" => "2"],
                ["kode_kabupaten" => "7501","provinsi_id" => "29","nama_kabupaten" => "KAB. GORONTALO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7502","provinsi_id" => "29","nama_kabupaten" => "KAB. BOALEMO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7503","provinsi_id" => "29","nama_kabupaten" => "KAB. BONE BOLANGO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7504","provinsi_id" => "29","nama_kabupaten" => "KAB. PAHUWATO","wilayah_id" => "1"],
                ["kode_kabupaten" => "7505","provinsi_id" => "29","nama_kabupaten" => "KAB. GORONTALO UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7571","provinsi_id" => "29","nama_kabupaten" => "KOTA GORONTALO","wilayah_id" => "2"],
                ["kode_kabupaten" => "7601","provinsi_id" => "30","nama_kabupaten" => "KAB. MAMUJU UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7602","provinsi_id" => "30","nama_kabupaten" => "KAB. MAMUJU","wilayah_id" => "1"],
                ["kode_kabupaten" => "7603","provinsi_id" => "30","nama_kabupaten" => "KAB. MAMASA","wilayah_id" => "1"],
                ["kode_kabupaten" => "7604","provinsi_id" => "30","nama_kabupaten" => "KAB. POLEWALI MANDAR","wilayah_id" => "1"],
                ["kode_kabupaten" => "7605","provinsi_id" => "30","nama_kabupaten" => "KAB. MAJENE","wilayah_id" => "1"],
                ["kode_kabupaten" => "7606","provinsi_id" => "30","nama_kabupaten" => "KAB. MAMUJU TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "8101","provinsi_id" => "31","nama_kabupaten" => "KAB. MALUKU TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "8102","provinsi_id" => "31","nama_kabupaten" => "KAB. MALUKU TENGGARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "8103","provinsi_id" => "31","nama_kabupaten" => "KAB MALUKU TENGGARA BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "8104","provinsi_id" => "31","nama_kabupaten" => "KAB. BURU","wilayah_id" => "1"],
                ["kode_kabupaten" => "8105","provinsi_id" => "31","nama_kabupaten" => "KAB. SERAM BAGIAN TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "8106","provinsi_id" => "31","nama_kabupaten" => "KAB. SERAM BAGIAN BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "8107","provinsi_id" => "31","nama_kabupaten" => "KAB. KEPULAUAN ARU","wilayah_id" => "1"],
                ["kode_kabupaten" => "8108","provinsi_id" => "31","nama_kabupaten" => "KAB. MALUKU BARAT DAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "8109","provinsi_id" => "31","nama_kabupaten" => "KAB. BURU SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "8171","provinsi_id" => "31","nama_kabupaten" => "KOTA AMBON","wilayah_id" => "2"],
                ["kode_kabupaten" => "8172","provinsi_id" => "31","nama_kabupaten" => "KOTA TUAL","wilayah_id" => "2"],
                ["kode_kabupaten" => "8201","provinsi_id" => "32","nama_kabupaten" => "KAB. HALMAHERA BARAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "8202","provinsi_id" => "32","nama_kabupaten" => "KAB. HALMAHERA TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "8203","provinsi_id" => "32","nama_kabupaten" => "KAB. HALMAHERA UTARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "8204","provinsi_id" => "32","nama_kabupaten" => "KAB. HALMAHERA SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "8205","provinsi_id" => "32","nama_kabupaten" => "KAB. KEPULAUAN SULA","wilayah_id" => "1"],
                ["kode_kabupaten" => "8206","provinsi_id" => "32","nama_kabupaten" => "KAB. HALMAHERA TIMUR","wilayah_id" => "1"],
                ["kode_kabupaten" => "8207","provinsi_id" => "32","nama_kabupaten" => "KAB. PULAU MOROTAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "8208","provinsi_id" => "32","nama_kabupaten" => "KAB. PULAU TALIABU","wilayah_id" => "1"],
                ["kode_kabupaten" => "8271","provinsi_id" => "32","nama_kabupaten" => "KOTA TERNATE","wilayah_id" => "2"],
                ["kode_kabupaten" => "8272","provinsi_id" => "32","nama_kabupaten" => "KOTA TIDORE KEPULAUAN","wilayah_id" => "2"],
                ["kode_kabupaten" => "9101","provinsi_id" => "33","nama_kabupaten" => "KAB. MERAUKE","wilayah_id" => "1"],
                ["kode_kabupaten" => "9102","provinsi_id" => "33","nama_kabupaten" => "KAB. JAYAWIJAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9103","provinsi_id" => "33","nama_kabupaten" => "KAB. JAYAPURA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9104","provinsi_id" => "33","nama_kabupaten" => "KAB. NABIRE","wilayah_id" => "1"],
                ["kode_kabupaten" => "9105","provinsi_id" => "33","nama_kabupaten" => "KAB. KEPULAUAN YAPEN","wilayah_id" => "1"],
                ["kode_kabupaten" => "9106","provinsi_id" => "33","nama_kabupaten" => "KAB. BIAK NUMFOR","wilayah_id" => "1"],
                ["kode_kabupaten" => "9107","provinsi_id" => "33","nama_kabupaten" => "KAB. PUNCAK JAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9108","provinsi_id" => "33","nama_kabupaten" => "KAB. PANIAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9109","provinsi_id" => "33","nama_kabupaten" => "KAB. MIMIKA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9110","provinsi_id" => "33","nama_kabupaten" => "KAB. SARMI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9111","provinsi_id" => "33","nama_kabupaten" => "KAB. KEEROM","wilayah_id" => "1"],
                ["kode_kabupaten" => "9112","provinsi_id" => "33","nama_kabupaten" => "KAB PEGUNUNGAN BINTANG","wilayah_id" => "1"],
                ["kode_kabupaten" => "9113","provinsi_id" => "33","nama_kabupaten" => "KAB. YAHUKIMO","wilayah_id" => "1"],
                ["kode_kabupaten" => "9114","provinsi_id" => "33","nama_kabupaten" => "KAB. TOLIKARA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9115","provinsi_id" => "33","nama_kabupaten" => "KAB. WAROPEN","wilayah_id" => "1"],
                ["kode_kabupaten" => "9116","provinsi_id" => "33","nama_kabupaten" => "KAB. BOVEN DIGOEL","wilayah_id" => "1"],
                ["kode_kabupaten" => "9117","provinsi_id" => "33","nama_kabupaten" => "KAB. MAPPI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9118","provinsi_id" => "33","nama_kabupaten" => "KAB. ASMAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "9119","provinsi_id" => "33","nama_kabupaten" => "KAB. SUPIORI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9120","provinsi_id" => "33","nama_kabupaten" => "KAB. MAMBERAMO RAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9121","provinsi_id" => "33","nama_kabupaten" => "KAB. MAMBERAMO TENGAH","wilayah_id" => "1"],
                ["kode_kabupaten" => "9122","provinsi_id" => "33","nama_kabupaten" => "KAB. YALIMO","wilayah_id" => "1"],
                ["kode_kabupaten" => "9123","provinsi_id" => "33","nama_kabupaten" => "KAB. LANNY JAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9124","provinsi_id" => "33","nama_kabupaten" => "KAB. NDUGA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9125","provinsi_id" => "33","nama_kabupaten" => "KAB. PUNCAK","wilayah_id" => "1"],
                ["kode_kabupaten" => "9126","provinsi_id" => "33","nama_kabupaten" => "KAB. DOGIYAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9127","provinsi_id" => "33","nama_kabupaten" => "KAB. INTAN JAYA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9128","provinsi_id" => "33","nama_kabupaten" => "KAB. DEIYAI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9171","provinsi_id" => "33","nama_kabupaten" => "KOTA JAYAPURA","wilayah_id" => "2"],
                ["kode_kabupaten" => "9201","provinsi_id" => "34","nama_kabupaten" => "KAB. SORONG","wilayah_id" => "1"],
                ["kode_kabupaten" => "9202","provinsi_id" => "34","nama_kabupaten" => "KAB. MANOKWARI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9203","provinsi_id" => "34","nama_kabupaten" => "KAB. FAK FAK","wilayah_id" => "1"],
                ["kode_kabupaten" => "9204","provinsi_id" => "34","nama_kabupaten" => "KAB. SORONG SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "9205","provinsi_id" => "34","nama_kabupaten" => "KAB. RAJA AMPAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "9206","provinsi_id" => "34","nama_kabupaten" => "KAB. TELUK BINTUNI","wilayah_id" => "1"],
                ["kode_kabupaten" => "9207","provinsi_id" => "34","nama_kabupaten" => "KAB. TELUK WONDAMA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9208","provinsi_id" => "34","nama_kabupaten" => "KAB. KAIMANA","wilayah_id" => "1"],
                ["kode_kabupaten" => "9209","provinsi_id" => "34","nama_kabupaten" => "KAB. TAMBRAUW","wilayah_id" => "1"],
                ["kode_kabupaten" => "9210","provinsi_id" => "34","nama_kabupaten" => "KAB. MAYBRAT","wilayah_id" => "1"],
                ["kode_kabupaten" => "9211","provinsi_id" => "34","nama_kabupaten" => "KAB. MANOKWARI SELATAN","wilayah_id" => "1"],
                ["kode_kabupaten" => "9212","provinsi_id" => "34","nama_kabupaten" => "KAB. PEGUNUNGAN ARFAK","wilayah_id" => "1"],
                ["kode_kabupaten" => "9271","provinsi_id" => "34","nama_kabupaten" => "KOTA SORONG","wilayah_id" => "2"]
            ]);
    }
}
